### ISSUE TITLE
Can't connect mongo via connection string inside Docker secrets

### ISSUE THREAD

**Issue by Satforst** [Graylog2/graylog2-server#11165]
Hi, 
I have three docker stacks inside Docker swarm:
Elasticsearch
MongoDB
Graylog
I`m not able to connect from Graylog to MongoDB, when I use environment GRAYLOG_MONGODB_URI_FILE. 
With GRAYLOG_MONGODB_URI as a string in compose file it works fine.
## Expected Behavior

Connect Graylog with MongoDB via connection string in docker secrets GRAYLOG_MONGODB_URI_FILE

## Current Behavior

Graylog isn`t able to connect to MongoDB
The log from Graylog is:
````
2021-08-16 13:32:25,199 INFO : org.mongodb.driver.cluster - Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000}

2021-08-16 13:32:25,233 INFO : org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out

2021-08-16 13:32:25,233 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017

com.mongodb.MongoSocketException: mongo: Name or service not known

at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[graylog.jar:?]

at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[graylog.jar:?]

at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[graylog.jar:?]

at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128) ~[graylog.jar:?]

at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [graylog.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

Caused by: java.net.UnknownHostException: mongo: Name or service not known

at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_292]

at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_292]

at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_292]

at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0_292]

at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_292]

at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_292]

at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203) ~[graylog.jar:?]

... 5 more
````

## Steps to Reproduce (for bugs)

1. Deploy stack with Elastic search.
* compose file:
```
version: '3.5'
services:
  elastic10:
    image: elasticsearch:7.9.3
    ports:
     # Elastic Host
     - target: 9200
       published: 9200
       protocol: tcp
       mode: host
    environment:
      - cluster.name=graylog-cluster
      - node.name=elastic10
      - discovery.seed_hosts=elastic10
      - cluster.initial_master_nodes=elastic10
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - elastic 
    deploy:
      mode: global
      resources:
        limits:
          CPU: '0.5'
          memory: 500M     
    deploy:
      placement:
        constraints:
          - node.hostname == docker-desktop
```
2. Deploy Mongo DB
* compose file:
```
version: '3.5'
services:
  mongo10:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_admin_pass
      MONGO_INITDB_ROOT_USERNAME: admin
    command: mongod --replSet rs1 --port 27017 --keyFile /etc/mongo-repl.key --bind_ip_all --dbpath /data --directoryperdb
    networks:
      - mongo
    secrets:
      - mongo_admin_pass
    volumes:
      - type: bind
        source: /gray-data
        target: /data
    configs:
      #- source: mongodb_config
      #  target: /etc/mongod.conf
      - source: mongodb_init
        target: /docker-entrypoint-initdb.d/graylog.js
      - source: mongoreplica_init
        target: /docker-entrypoint-initdb.d/graylogreplica.js
      - source: mongodb_key
        target: /etc/mongo-repl.key
        uid: '999'
        gid: '999'
        mode: 0600
    deploy:
      placement:
        constraints:
          - node.hostname == docker-desktop
```
* mongo.conf
```
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/
storage:
  engine: wiredTiger
  dbPath: /data
  directoryPerDB: true
  journal:
    enabled: true

# where to write logging data.
systemLog:
  quiet: true
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0

security:
  keyFile: /etc/mongo-repl.key

replication:
  replSetName: rs1
```
*  mongo_init
```
graylog = db.getSiblingDB('graylogdb');
graylog.createUser(
  {
    user: "graylog",
    pwd: "password",
    roles: [
      { role: "dbOwner", db: "graylogdb" }
    ]
  }
);
```
3. Deploy Graylog:
* compose file:
```
version: '3.5'
services:
  graylog10:
    image: graylog2/graylog:4.0
    ports:
     # Graylog WEB interface
     - target: 9001
       published: 9001
       protocol: tcp
       mode: host
     # GELF TCP
     - target: 12201
       published: 12201
       protocol: tcp
       mode: host
     # GELF UDP
     - target: 12201
       published: 12201
       protocol: udp
       mode: host
     # SYSLOG TCP
     - target: 5514
       published: 5514
       protocol: tcp
       mode: host
     # SYSLOG UDP
     - target: 5514
       published: 5514
       protocol: udp
       mode: host
     # RAW / PLAINTEXT TCP
     - target: 5555
       published: 5555
       protocol: tcp
       mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == docker-desktop
    environment:
      GRAYLOG_IS_MASTER: "true"
      GRAYLOG_NODE_ID_FILE: /etc/graylog/server/node-id
      GRAYLOG_PASSWORD_SECRET: secret_password
      GRAYLOG_ROOT_USERNAME: admin
      GRAYLOG_ROOT_PASSWORD_SHA2_FILE: /run/secrets/graylog_root_sha2
      GRAYLOG_PLUGIN_DIR: /usr/share/graylog-server/plugin
      GRAYLOG_WEB_ENABLE: "true"
      GRAYLOG_REST_LISTEN_URI: http://localhost:9001/api/
      GRAYLOG_WEB_LISTEN_URI: http://localhost:9001/
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9001
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elastic10:9200
      GRAYLOG_ROTATION_STRATEGY: count
      GRAYLOG_ELASTICSEARCH_INDEX_PREFIX: graylog
      GRAYLOG_OUTPUT_BATCH_SIZE: 1000
      GRAYLOG_OUTPUT_FLUSH_INTERVAL: 1
      GRAYLOG_PROCESSBUFFER_PROCESSORS: 20
      GRAYLOG_OUTPUTBUFFER_PROCESSORS: 12
      GRAYLOG_RING_SIZE: 16777216
      GRAYLOG_INPUTBUFFER_RING_SIZE: 16777216
      GRAYLOG_INPUTBUFFER_PROCESSORS: 4
      GRAYLOG_MESSAGE_JOURNAL_ENABLED: "false"
      ### If you uncomment line below and comment GRAYLOG_MONGODB_URI_FILE it`ll work
      ##GRAYLOG_MONGODB_URI: mongodb://graylog:password@mongo10:27017,mongo11:27017,mongo12:27017/graylogdb?replicaSet=rs1
      GRAYLOG_MONGODB_URI_FILE: /run/secrets/graylog_mongo_pass
      GRAYLOG_MONGODB_MAX_CONNECTIONS: 1000
      GRAYLOG_MONGODB_THREADS_ALLOWED_TO_BLOCK_MULTIPLIER: 5
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
      GRAYLOG_CONTENT_PACKS_DIR: /usr/share/graylog-server/contentpacks
      GRAYLOG_CONTENT_PACKS_AUTO_LOAD: grok-patterns.json
      GRAYLOG_SERVER_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - type: volume
        source: graylog_contentpacks
        target: /usr/share/graylog-server/contentpacks
      - type: volume
        source: graylog_plugin
        target: /usr/share/graylog-server/plugin
      - type: bind
        source: ./configs/GeoLite2-City.mmdb
        target: /etc/graylog/server/GeoLite2-City.mmdb
    configs:
      - source: graylog_node10-id
        target: /etc/graylog/server/node-id
    secrets:
      - graylog_root_sha2
      - graylog_mongo_pass
    networks:
      - graylog
      - mongo
      - elastic

configs:
  graylog_node10-id:
    file: ./configs/node10-id

volumes:
  graylog_contentpacks:
  graylog_plugin:

secrets:
  graylog_root_sha2:
    external: true
  graylog_mongo_pass:
    external: true

networks:
  graylog:
    external: true
  mongo:
    external: true
  elastic:
    external: true
```
* graylog_node10-id
```
docker-desktopid
```
The Docker secret GRAYLOG_MONGODB_URI_FILE have the same string as is in GRAYLOG_MONGODB_URI

* Graylog Version: graylog2/graylog:4.0
* Elasticsearch Version: elasticsearch:7.9.3
* MongoDB Version: mongo:4.4
* Operating System: Ubuntu 16.04.7
