### ISSUE TITLE
Using TCK Tested JDK builds of OpenJDK 

### ISSUE THREAD

**Issue by carldea** [Graylog2/graylog2-server#11467]
GitHub Action `setup-java@v2` requires a distribution templeted with `adopt`.  The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). Switching the distribution to Azul Zulu (`zulu`). When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. AdoptOpenJDK builds are not TCK tested.

## Expected Behavior

When building and testing the project you are expected to get the latest JDK (security patches, bug fixes, etc.). Or a major fixed version from an archived release. This is good practice if there are major vendors and customers who are still using older versions of the JDK.

## Current Behavior

- Not getting the latest JDK release
- Not building and testing on TCK tested JDK
- Only testing and building on the latest JDK

## Possible Solution

Update github actions to use `zulu` as a distro will solve the following:

- Gets the latest builds of OpenJDK
- Azul Zulu builds are TCK tested (ready for production)
- Provide a matrix to test/build a fixed(major) version and the latest.

The following snippet will be added to the GitHub workflow:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        java-version: [ 8.0.192, 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
```

## Context

Full disclosure, I work for Azul and I would like to help repos/projects avoid test/build interuptions because of `OpenJDK` distribution build versions provided from GH `setup-java@v2` are not consistent (except `zulu`). Originally GH action `setup-java@v1` was using `zulu` and the newer version (GHAction) allows you to choose `adopt`, `zulu`, and `temurin`. Because adopt has been discontinued (AdoptOpenJDK binaries) you only have two choices currently. 
  
## Your Environment

N/A
