### ISSUE TITLE
Graylog 4.3: need to document opensearch usage

### ISSUE THREAD

**Issue by JaneJeon** [Graylog2/graylog2-server#12735]
Hi, I'm trying to setup graylog w/ opensearch (at long last), but many parts of the docs have not been updated, such as here: https://docs.graylog.org/v1/docs/docker#settings

For this issue, it would suffice to have a minimal docker compose file w/ opensearch, but in general you guys should go through the docs and have an opensearch equivalent documentation for every elasticsearch documentation.

**Comment by loganmarchione** [comment]
Does this example help?

https://github.com/Graylog2/graylog2-server/pull/11435#issuecomment-958941049

**Comment by logopk** [comment]
@loganmarchione 
I'd say no!
- Do I have to update my graylog config? Just ip or name of the container?
- how will data be migrated? Any idea how long that will take? Will there be downtime? 

that should be a quite detailed migration documentation.

Very much appreciated!

Peter

**Comment by JaneJeon** [comment]
@loganmarchione Could you update the specific section I mentioned in the docs, or at least add sections in the docs for using graylog w/ opensearch? There's currently nothing in the docs, and while I'll take your example, the docs really need to be expanded for me to consider running graylog w/ opensearch in production.

**Comment by JaneJeon** [comment]
Whoops my b

**Comment by loganmarchione** [comment]
I was able to get this to work (in Docker Compose). I did not even attempt to migrate any data in the volumes, so I'm basically starting a test cluster from scratch. The example below does not have any Mongo or Graylog container definitions (obviously).

```
...
...
...
  opensearch:
    container_name: graylog_opensearch
    image: opensearchproject/opensearch:1.3.1
    restart: unless-stopped
    environment:
      - plugins.security.disabled=true
      - node.name=graylog-server
      - cluster.name=graylog
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - opensearch
      - graylog
      - monitoring
    volumes:
      - 'opensearch_data:/usr/share/opensearch/data'

...
...
...

networks:
  opensearch:
volumes:
  opensearch_data:
    driver: local
...
...
...
```

I also had to change the `graylog.conf` file to point to the new container name.
```
elasticsearch_hosts = http://opensearch:9200
```
