### ISSUE TITLE
Processor stops processing after a short time

### ISSUE THREAD

**Issue by tslytsly** [Graylog2/graylog2-server#12949]
## Expected Behavior
Processor should continue to process messages.

## Current Behavior
After a short time of restarting the server, the processor stops processing messages and the journal fills up.
We see this in the log:
```
2022-06-17 11:21:57,189 ERROR: com.google.common.util.concurrent.ServiceManager - Service LocalKafkaMessageQueueReader [FAILED] has failed in the RUNNING state.
java.lang.IllegalStateException: Invalid message size: 0
        at org.graylog.shaded.kafka09.log.FileMessageSet.searchFor(FileMessageSet.scala:141) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.translateOffset(LogSegment.scala:105) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.read(LogSegment.scala:148) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.Log.read(Log.scala:506) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:677) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.readNext(LocalKafkaJournal.java:617) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:599) ~[graylog.jar:?]
        at org.graylog2.shared.messageq.localkafka.LocalKafkaMessageQueueReader.run(LocalKafkaMessageQueueReader.java:110) ~[graylog.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:67) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
```

Oddly enough, if I have the Graylog logging set to Trace, then the issue does not occur, it is only when the logging is set to Debug or below that it will happen.

## Possible Solution
Unknown, have tried multiple things to resolve, no success.

## Steps to Reproduce (for bugs)
1. Enable Syslog UDP input
2. Send Syslogs

## Context
We use Graylog to consume and index UDP syslog messages, mostly from Wildix cloud PBXes.
The issue does not seem to be related to the load on the system, it will happen with 7000 logs per second, or 10.

## Your Environment
Graylog running as a container.
Docker server is UnRAID 6.10.2
ES also running as a Container, version 6.6.2 (have also tried version 7)

* Graylog Version: 4.3.2
* Java Version: openjdk-8 (included in official Graylog docker)
* Elasticsearch Version: 6.6.2
* MongoDB Version: 4.2.21
* Operating System: UnRAID 6.10.2
* Browser version: Chrome 103.0.5060.53

**Comment by avandeputte** [comment]
I am having the exact same issue,  on unraid 6.10.3

**Comment by tslytsly** [comment]
I have now tried this with a completely fresh and default install of Graylog, ES and Mongo. All new containers with no previous config. Same result.

**Comment by tkohhh** [comment]
I am also getting this error after updating Unraid to 6.10.3 from 6.9.2.

**Comment by tslytsly** [comment]
So it seems to be linked to the unRAID OS possibly. 
Any ideas on ways to capture the correct data work out what the issue is? 
I'm happy to test things and provide logs, etc.

**Comment by Kieffer87** [comment]
Also having this issue. I recently re-built all 3 containers switching to ES 7.10.1 and thought it was something to do with that. 

- unraid 6.10.3
- graylog 4.3.2+313b6bc
- elasticsearch 7.10.1

**Comment by tkohhh** [comment]
This problem is still persistent after updating to graylog 4.3.3

How can we get the developers to look at this issue?

**Comment by moesterheld** [comment]
Hi,
I'm trying to reproduce the issue. Are you all using the ES, Mongo and Graylog Apps / Containers provided by the Community App Marketplace?
Did the issue only occur after updating to UnraidOS 6.10.3?
Thanks,
Matthias

**Comment by tslytsly** [comment]
> Hi, I'm trying to reproduce the issue. Are you all using the ES, Mongo and Graylog Apps / Containers provided by the Community App Marketplace? Did the issue only occur after updating to UnraidOS 6.10.3? Thanks, Matthias

Yes, using the apps from the community app marketplace.
I've tried both Elasticsearch containers.
MongoDB is the one provided by Taddeusz's Repository

The issue does seem to coincide with the upgrade to 6.10.2 for me (not tried .3 yet)
Before that Graylog was ingesting 1000s of logs per second with no issues.

**Comment by tkohhh** [comment]
I'm using docker compose as described here: https://whitematter.tech/posts/run-graylog-with-docker-compose-on-unraid/

Repositories are: 
mongo:5.0
docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
graylog/graylog:4.3.3

Prior to updating to Unraid 6.9.2, there were no issues.  Currently I'm running with logging set to Trace, since the problem does not happen when logging is set to Trace.  Let me know if you need any more information!

**Comment by mpfz0r** [comment]
Would it possible to get us the content of your `data/journal` directory once you've triggered that issue?
Be aware that this could contain some of your log data, so only share if that's okay with you.
You could send it by mail

**Comment by Kieffer87** [comment]
@mpfz0r let me know the best way to share privately and I can get mine sent to you. Looks like it's 56MB.

**Comment by mpfz0r** [comment]
@Kieffer87 could send me a mail to marco _at_ graylog.org ?
I will be in touch

**Comment by tkohhh** [comment]
If you need a second example of the data/journal directories, let me know!

**Comment by Kieffer87** [comment]
@mpfz0r email sent.

**Comment by tslytsly** [comment]
@moesterheld thanks for your help with this.
Just in case it is relevant, I'm seeing the issue even if I have logging set to trace.

**Comment by tkohhh** [comment]
I just want to report that this is still an issue after upgrading to Graylog 4.3.4

**Comment by DrDirtyDevil** [comment]
i have the same issue, also the same situation as above Unraid 6.10.3 with docker compose

**Comment by DrDirtyDevil** [comment]
to be a bit more specific I only started using graylog since yesterday so it is a completely new install which has the exact same issue.

**Comment by moesterheld** [comment]
Does your journal share use the cache pool of UnraidOS? Could you maybe try to move it to a different share without caching?
Does this only occur with Syslog UDP inputs? Could you maybe also try a Random HTTP message generator input?

Thank you,
Matthias

**Comment by tkohhh** [comment]
My journal does indeed reside on an Unraid "cache pool", but that particular share is set to "Cache:prefer".  This means it permanently lives on the cache pool and is never moved (this is typical for Unraid).  I will try moving it if you think it will make a difference, but I wanted to make sure you understand that the journal files are not being moved around at any time.

As for my inputs, I currently have the following enabled and receiving messages:

- Beats
- GELF TCP
- GELF UDP
- Syslog TCP
- Syslog UDP

It's not clear that any of these in particular trigger the error, but I can try to take a look at that today.

Are you suggesting that I disable all inputs, and then create a Random HTTP message input to see if the error is still triggered?

**Comment by DrDirtyDevil** [comment]
I moved the journal to the array directly to see if that makes a difference 

I only use syslog udp however 

i wil get back to you if I have an update.

**Comment by moesterheld** [comment]
If it is possible for you to move the share to use the filesystem, that would be great. Just want to make sure the cache is not the culprit here. 
As for the inputs, it would be great if we could make sure it's not connected to a particular input type. The Random HTTP would be useful since there is no networking involved to see if we can reproduce the error with this input type alone.

I have also set up a test UnraidOS system now, which has been happily ingesting 60 syslog messages / minute for the last two hours (also using a cached share). Syslogs are pushed in from the UnraidOS host itself and another Docker container. The problem should probably already have occured, right?
It is a very simple system with a single xfs data disk, no parity disk and only the Graylog environment running. Maybe we can figure out if a configuration change causes the issue.

**Comment by tkohhh** [comment]
Respectfully, I think you may be misunderstanding how Unraid cache works.  The cache pool IS part of the file system... it's just another drive (usually an SSD for the speed benefits).  If you set up a simple system with only a single data drive, then you will not have any caching regardless of your share cache settings.

For the sake of ruling out potential issues, I will do the following:

1. Move the journal to a share on my array.  I will run with the existing inputs and see if the error occurs.
2. Then, I will disable all of the inputs and add a Random HTTP input and see if the error occurs.

Thanks for your help with this... I'll report back with my findings!

**Comment by moesterheld** [comment]
@tkohhh Thanks for the input. I was thinking Unraid is using an in-memory cache.

**Comment by tkohhh** [comment]
Here are my findings:

1. Moving the journal to the array (instead of the cache pool) had no effect.  I received the error after about 15 minutes.
2. Disabling all of my inputs and enabling a Random HTTP input has been running for 30 minutes now without the error.

I'm starting to wonder if it's the Unraid syslog that is causing the error.  I have the Unraid syslog set up to use syslog TCP.  Did you set it up with TCP or UDP on your test system?

I'm going to let just the Random HTTP run for a while longer just to make sure, and then I will do the following:

1. Disable remote logging in Unraid settings, and then re-enable all of my Graylog inputs.
2. If that runs without the error, then I will re-enable remote logging in Unraid, but use UDP instead of TCP.

**Comment by tkohhh** [comment]
OK... that may be good news.  I've been running for the last hour with the Unraid remote logging disabled, and no error.  I'm going to turn it on with UDP now and see what happens.

To the other users that have reported this error: is your Unraid remote logging using TCP or UDP?

**Comment by tslytsly** [comment]
Hi,
I have this issue on 2 unRAID servers.
One has remote syslogging enabled using UDP to the Graylog docker.
The other has syslogging disabled. 🤷‍♀️

Tom

**Comment by tkohhh** [comment]
UDP did generate the error after about 90 minutes.  I'm going back to disabling the Unraid remote logging.  I'll let it run for longer this time to see if I get the error.

**Comment by tkohhh** [comment]
I can now confirm that the error does indeed occur even with the Unraid remote logging disabled.  I received the error about 55 minutes after restarting Graylog.

So, there goes that theory!

@moesterheld what other information can we provide to help get to the bottom of this?

**Comment by moesterheld** [comment]
Good morning,
just to clarify: There are also no other syslogs coming in from containers? And you could reproduce it with the Http Random Message Input?
I suppose you're all using parity disks? If so, I would try to add one to my setup.

**Comment by DrDirtyDevil** [comment]
Interesting, we kind of came to the conclusion that moving the journal to the array didn't help. 

I have so far ONLY moved the journal to the array no other changes whatsoever and mine has been up for 12 hours now.

I have all UDP syslog running on 6 ports from different sources including unraid itself.

**Comment by DrDirtyDevil** [comment]
i am indeed running with 2 parity disks

**Comment by tslytsly** [comment]
I'll try moving the journal off the cache pool, see if it helps

**Comment by tkohhh** [comment]
> Good morning,
> just to clarify: There are also no other syslogs coming in from containers? And you could reproduce it with the Http Random Message Input?
> I suppose you're all using parity disks? If so, I would try to add one to my setup.

I have one other syslog in addition to the Unraid syslog that is writing to Graylog.  In addition, I have several docker containers that are writing to Graylog via GELF (both TCP and UDP).

I did not reproduce the error using HTTP Random, but I will set that up and let it run all day today to confirm.

I have a single parity disk on my array.

**Comment by DrDirtyDevil** [comment]
I wish I could be of more help but so far changing my journal to the array still has helped for some strange reason. the processor is now up for 19 hours and counting... I did not change a thing besides the mounting location of the journal.

**Comment by DrDirtyDevil** [comment]
Mine just went offline again, it tried its best.... 

https://screenshots.maaslandjes.nl/iilL7nlOFsoavSxsSin8

**Comment by tkohhh** [comment]
HTTP Random has been running without error for the last 24 hours.  I'm inclined to conclude that the error is not present when using only HTTP Random.

**Comment by marcelhaerle** [comment]
Same error on my Unraid server:

- Unraid 6.10.3
- Graylog 4.3.3
- Elasticsearch 7.10.1
- MongoDB 5.0.10

Graylog, elasticsearch and MongoDB installed as Docker "apps". I have several Syslog UDP inputs, where I collect syslogs from different linux servers and pfSense filterlogs. The message processing stops after 1-6 hours. It does not matter if there is low (<5 messages per second) or higher load (>100 messages per second) on the server. The journal and elastic data directory is on a cache-only share. My graylog server crashes no matter if unraid remote syslog is enabled or disabled.

The Graylog server dies after logging this stacktrace:

```
2022-08-16 22:41:06,945 ERROR: com.google.common.util.concurrent.ServiceManager - Service LocalKafkaMessageQueueReader [FAILED] has failed in the RUNNING state.
java.lang.IllegalStateException: Invalid message size: 0
        at org.graylog.shaded.kafka09.log.FileMessageSet.searchFor(FileMessageSet.scala:141) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.translateOffset(LogSegment.scala:105) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.read(LogSegment.scala:148) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.Log.read(Log.scala:506) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:677) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.readNext(LocalKafkaJournal.java:617) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:599) ~[graylog.jar:?]
        at org.graylog2.shared.messageq.localkafka.LocalKafkaMessageQueueReader.run(LocalKafkaMessageQueueReader.java:110) ~[graylog.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:67) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
```

After restarting the graylog container, the journal data gets processed and the server runs again for several hours.

**Comment by mpfz0r** [comment]
In case you need a workaround, running without the journal should work. (`message_journal_enabled  = false`)
Be aware that, you might lose some data from UDP inputs, if Graylog cannot keep up with bursts.

BTW: Has anyone who is testing this with just the random HTTP input tried to lower the sleep time?

**Comment by Kieffer87** [comment]
Thanks for the workaround @mpfz0r, graylog has been up and running for a few hours now without any crashes.

**Comment by tkohhh** [comment]
> BTW: Has anyone who is testing this with just the random HTTP input tried to lower the sleep time?

I think I'm the only one who tested with the HTTP input.  I used 1000/500 for sleep time, which approximates my throughput.  As the OP and others have noted, this issue does not appear to correlate with high load.

**Comment by DrDirtyDevil** [comment]
i have downgraded unraid to 6.9.2 and it is working for 72 hours now without any issues

**Comment by DrDirtyDevil** [comment]
I Downgraded to unraid 6.9.2 and I have been running for over 72 hours without issues now.

**Comment by tkohhh** [comment]
Just want to report that this issue is still present in Graylog 4.3.7

**Comment by logopk** [comment]
Same error message on docker 4.3.8 on debian.

Seems to me that the journal is corrupt and it does not process beyond this broken entry and only adds new message to the journal.

**Comment by logopk** [comment]
To solve the problem I've deleted the old message-journal file (<id>.index <id>.log) and restarted graylog.

**Comment by jasonkuehl** [comment]
Testing with (message_journal_enabled = false) in my docker file. I also starting having the same issue on a new setup on Version: 6.11.1 on unriad. 

graylog Graylog v4.3.8+8c4705e
elasticsearch 6.8.23
MonogDB  4.2.23

**Comment by jasonkuehl** [comment]
That didnt last long  :(

`2022-10-23 19:36:24,623 ERROR: com.google.common.util.concurrent.ServiceManager - Service LocalKafkaMessageQueueReader [FAILED] has failed in the RUNNING state.
java.lang.IllegalStateException: Invalid message size: 0
        at org.graylog.shaded.kafka09.log.FileMessageSet.searchFor(FileMessageSet.scala:141) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.translateOffset(LogSegment.scala:105) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.read(LogSegment.scala:148) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.Log.read(Log.scala:506) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:677) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.readNext(LocalKafkaJournal.java:617) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:599) ~[graylog.jar:?]
        at org.graylog2.shared.messageq.localkafka.LocalKafkaMessageQueueReader.run(LocalKafkaMessageQueueReader.java:110) ~[graylog.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:67) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]`

**Comment by AlexNewson** [comment]
I'm getting the same issue, for a fresh install Graylog can last anywhere from 3 hours to 15 mins. All produce the same issue:

```
2022-11-20 12:44:23,526 ERROR: com.google.common.util.concurrent.ServiceManager - Service LocalKafkaMessageQueueReader [FAILED] has failed in the RUNNING state.
java.lang.IllegalStateException: Invalid message size: 0
        at org.graylog.shaded.kafka09.log.FileMessageSet.searchFor(FileMessageSet.scala:141) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.translateOffset(LogSegment.scala:105) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.LogSegment.read(LogSegment.scala:126) ~[graylog.jar:?]
        at org.graylog.shaded.kafka09.log.Log.read(Log.scala:506) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:677) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.readNext(LocalKafkaJournal.java:617) ~[graylog.jar:?]
        at org.graylog2.shared.journal.LocalKafkaJournal.read(LocalKafkaJournal.java:599) ~[graylog.jar:?]
        at org.graylog2.shared.messageq.localkafka.LocalKafkaMessageQueueReader.run(LocalKafkaMessageQueueReader.java:110) ~[graylog.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:67) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
```

After following @logopk and deleting the old message-journal file (`rm -r ./*` in Unraid's `appdata/graylog`) I can start collecting stats again until a later crash.

**Versions**

Unraid: 6.11.2
Graylog: 4.3.9 (graylog/graylog)
Elasticsearch: 7.10.2 (d8sychain/elasticsearch)
MongoDB: 6.0.3 (mongo)

**Comment by AlexNewson** [comment]
Can confirm [workaround](https://github.com/Graylog2/graylog2-server/issues/12949#issuecomment-1219146839) from @mpfz0r. Have been up and running for nearly a week now.

**Comment by antbarney** [comment]
Just to add the data point I am also hitting this same error. using the latest docker compose example that is using opensearch.
Currently I have a Unraid, PfSense, and a Few Unifi AP's writing to syslog over UDP.

**Version:**
Unraid: 6.11.2
Graylog: graylog/graylog:5.0 (5.0.2+59d96f8, codename Noir )
Opensearch: opensearchproject/opensearch:2.4.0
MongoDB: mongo:5.0


I can also confirm that using @mpfz0r workaround does work. By adding GRAYLOG_MESSAGE_JOURNAL_ENABLED: false to my docker compose file. 

Here is my config for reference
```
version: "3.8"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      nofile: 64000
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      TZ: "America/Los_Angeles"
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_MESSAGE_JOURNAL_ENABLED: false
    ports:
    #- "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    #- "5555:5555/tcp"   # RAW TCP
    #- "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    #- "12201:12201/tcp" # GELF TCP
    #- "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/config"
      - "graylog_journal:/usr/share/graylog/data/journal"
      - "graylog_log:/usr/share/graylog/data/log"
      - "graylog_plugin:/usr/share/graylog/data/plugin"
      - "graylog_content:/usr/share/graylog/data/contentpacks"
    restart: "on-failure"

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/mongodb_data
  os_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/os_data
  graylog_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/graylog_data
  graylog_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/graylog_log
  graylog_plugin:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/graylog_plugin
  graylog_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/graylog_content
  graylog_journal:
    driver: local
    driver_opts:
      type: none
      o: bind
      # This directory specified where InvenTree data are stored "outside" the docker containers
      # Change this path to a local system path where you want InvenTree data stored
      device: /mnt/user/appdata/graylog/graylog_journal


networks:
  default:
    name: comproxy
    external: true
```
