### ISSUE TITLE
Bug while upgrading from 4.3.3

### ISSUE THREAD

**Issue by gotschi** [Graylog2/graylog2-server#13573]
Trying to upgrade from 4.3.3 I get OOM errors.
I think this is a bug because there is nobody in the forums who could help me with this.
https://community.graylog.org/t/upgrading-from-4-3-3/25926/4

Here is the output with `4.3.5-jre11` (or anything > 4.3.3) : (fails)
https://x0.at/kB3v.txt

Here is the output with `4.3.3-jre11`: (successful, normal start)
https://x0.at/NEGO.txt

## Expected Behavior
Upgrading the Container to > 4.3.3 will work just fine

## Current Behavior
Upgrade of Container Image refuses to start, Out of memory Error

## Steps to Reproduce (for bugs)
my `docker-compose.yml` :
```yaml
version: "3"

services:
  mongodb:
    container_name: mongodb
    image: "mongo:4.2"
    volumes:
      - "/media/satahdd/docker-graylog/mongodb_data:/data/db"
    restart: "always"

  elasticsearch:
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "/media/satahdd/docker-graylog/es_data:/usr/share/elasticsearch/data"
    restart: "always"

  graylog:
    image: "graylog/graylog:4.3.3"
    container_name: graylog
    depends_on:
      - elasticsearch
      - mongodb
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: ...
      GRAYLOG_ROOT_PASSWORD_SHA2: ...
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:7000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:7000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5141:5141/udp"   # Opnsense Syslog
    - "5142:5142/udp"   # OpenWRT Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "7000:7000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    - "12401:12401/udp"
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - ./GeoLite2-City.mmdb:/etc/graylog/server/GeoLite2-City.mmdb
      - "/media/satahdd/docker-graylog/graylog_data:/usr/share/graylog/data/data"
      - "/media/satahdd/docker-graylog/graylog_journal:/usr/share/graylog/data/journal"
    restart: "always"
```

When I change to `graylog:4.3.4`(no matter if with "-jdk" or without) it fails with the errors linked above.

## Context
Trying to update, never had trouble but am stuck with 4.3.3 for now it seems, no idea why I get OOM

## Your Environment
i7 6th gen, 50 gigs ram (of which at least 40gb is free/available to Graylog at all times)
* Graylog Version: 4.3.4
* Java Version: containerized
* Elasticsearch Version: containerized
* MongoDB Version: containerized
* Operating System: debian 10
* Browser version: Chrome
