### ISSUE TITLE
[Docker Compose] `Unable to retrieve version from Elasticsearch node`

### ISSUE THREAD

**Issue by AnonymousWP** [Graylog2/graylog2-server#14174]
When using a Docker Compose file to run Graylog 5.0 in combination with MongoDB 6 and OpenSearch 2.3, it results in an error that the host can't be found.

## Expected Behavior

The containers should be able to connect to each other, and the documentation should be updated accordingly about how to properly use OpenSearch 2.x in combination with Graylog 5.0 in a Docker Compose file.

## Current Behavior

When running `docker-compose up`, Graylog can't connect to OpenSearch 2.3:

```
graylog_1     | 2022-12-09 12:27:39,420 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Unknown host 'elasticsearch: Name or service not known'. - Unknown host 'elasticsearch: Name or service not known'.
graylog_1     | 2022-12-09 12:27:39,421 INFO : org.graylog2.storage.versionprobe.VersionProbe - Elasticsearch is not available. Retry #5
```

It seems like I have to specify the version in the Docker Compose file as environment variable, but I've tried this (I used `GRAYLOG_ELASTICSEARCH_VERSION=7`, but also tried `GRAYLOG_ELASTICSEARCH_VERSION=7.10.2` and `GRAYLOG_ELASTICSEARCH_VERSION=2.3`), which doesn't work.

## Possible Solution

I think the error lies in my Docker Compose file, but I can't really come up with what else I could try. There are existing/closed issues about it, but not with this combination (Graylog 5.0 + MongoDB 6 + OpenSearch 2.3 in Docker Compose).

## Steps to Reproduce (for bugs)

1. Use the following Docker Compose file
```
version: '3.7'
services:

  mongo:
    image: mongo:6.0.3
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.3.0

     # Stores OpenSearch data in this directory/path. Comes in handy when updating OpenSearch, so that data is retained.
    volumes:
      - es_data:/usr/share/opensearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g" # `Xms` specifies the initial memory allocation pool. `Xmx` specifies the maximum allocation pool for the Java Virtual Machine (JVM). "m" and "g" obviously stand for MB and GB.
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog
    restart: always

  graylog:
    image: graylog/graylog:5.0.0
    volumes:
      - graylog_data:/usr/share/graylog/data # Stores Graylog data in this directory/path. Comes in handy when updating Graylog, so that data is retained.
    environment:
      - GRAYLOG_PASSWORD_SECRET=<your-secret>

      - GRAYLOG_ROOT_PASSWORD_SHA2=<your-sha2> # You can generate the SHA256-hash of your password with `echo -n <password> | sha256sum`

      - GRAYLOG_HTTP_EXTERNAL_URI=http://<your-uri>:9000/ # You can change the IP-address to 127.0.0.1 if you want to run it locally, and any external IP-address if you want to run it on a server.

      - GRAYLOG_ELASTICSEARCH_VERSION=7.10.2
 
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog

    # Links MongoDB with OpenSearch.
    links:
      - mongo:mongodb
      - opensearch
    restart: always

    #Doesn't work without MongoDB and OpenSearch.
    depends_on:
      - mongo
      - opensearch
    ports:
      - 5044:5044/udp       # Beats UDP
      - 5044:5044/tcp        # Beats TCP
      - 9000:9000              # Graylog web interface and REST API
      - 1514:1514/udp      # Syslog UDP
      - 5555:5555/tcp       # Raw/Plaintext TCP input
networks:
    graylog:
      driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
```

2. Notice how the following output is returned:

```
graylog_1     | 2022-12-09 12:27:39,420 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Unknown host 'elasticsearch: Name or service not known'. - Unknown host 'elasticsearch: Name or service not known'.
graylog_1     | 2022-12-09 12:27:39,421 INFO : org.graylog2.storage.versionprobe.VersionProbe - Elasticsearch is not available. Retry #5
graylog_1     | 2022-12-09 12:27:44,424 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Unknown host 'elasticsearch'. - Unknown host 'elasticsearch'.
graylog_1     | 2022-12-09 12:27:44,427 INFO : org.graylog2.storage.versionprobe.VersionProbe - Elasticsearch is not available. Retry #6
graylog_1     | 2022-12-09 12:27:49,431 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Unknown host 'elasticsearch: Name or service not known'. - Unknown host 'elasticsearch: Name or service not known'.
graylog_1     | 2022-12-09 12:27:49,432 INFO : org.graylog2.storage.versionprobe.VersionProbe - Elasticsearch is not available. Retry #7
```

## Your Environment

* Graylog Version: 5.0
* Java Version: whatever the image comes with
* Elasticsearch Version: OpenSearch 2.3
* MongoDB Version: 6.0.3
* Operating System: Ubuntu 20.04
* Browser version: Chrome 109

**Comment by dennisoelkers** [comment]
Hey @AnonymousWP,

debugging your docker-compose file is a bit out of scope for a github issue, as we use these for tracking bugs or feature requests. But what you could try is to add a `GRAYLOG_ELASTICSEARCH_HOSTS=https://opensearch:9200` environment variable for your `graylog` host. Also, you should remove the `GRAYLOG_ELASTICSEARCH_VERSION=7.10.2` setting.

**Comment by janheise** [comment]
Hi @AnonymousWP, what you describe might not be the root of the problem. OpenSearch2 comes with HTTPS enabled per default, if you want to use it like that, you have to disable it.
`      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
`

**Comment by AnonymousWP** [comment]
> Hey @AnonymousWP,
> 
> debugging your docker-compose file is a bit out of scope for a github issue, as we use these for tracking bugs or feature requests. But what you could try is to add a `GRAYLOG_ELASTICSEARCH_HOSTS=https://opensearch:9200` environment variable for your `graylog` host. Also, you should remove the `GRAYLOG_ELASTICSEARCH_VERSION=7.10.2` setting.

Hi,

First of all: thanks for your help.

Yeah, I thought so, but the Docker Compose repo of Graylog is pretty much dead. Your suggestions unfortunately result in the same error. Any chance the documentation regarding Graylog & Docker Compose could be updated accordingly?



> Hi @AnonymousWP, what you describe might not be the root of the problem. OpenSearch2 comes with HTTPS enabled per default, if you want to use it like that, you have to disable it. ` - "plugins.security.ssl.http.enabled=false" - "plugins.security.disabled=true"` also, what @dennisoelkers said re: removing the 7.10.2 compatibility setting

Thanks, I tried this as well, but it's not helping. My Docker Compose file looks like this right now:

```
version: '3.7'
services:

  mongo:
    image: mongo:6.0.3
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.3.0

     # Stores OpenSearch data in this directory/path. Comes in handy when updating OpenSearch, so that data is retained.
    volumes:
      - es_data:/usr/share/opensearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g" # `Xms` specifies the initial memory allocation pool. `Xmx` specifies the maximum allocation pool for the Java Virtual Machine (JVM). "m" and "g" obviously stand for MB and GB.
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog
    restart: always

  graylog:
    image: graylog/graylog:5.0.0
    volumes:
      - graylog_data:/usr/share/graylog/data # Stores Graylog data in this directory/path. Comes in handy when updating Graylog, so that data is retained.
    environment:
      - GRAYLOG_PASSWORD_SECRET=<your-secret>

      - GRAYLOG_ROOT_PASSWORD_SHA2=<your-sha2> # You can generate the SHA256-hash of your password with `echo -n <password> | sha256sum`

      - GRAYLOG_HTTP_EXTERNAL_URI=http://<your-uri>:9000/ # You can change the IP-address to 127.0.0.1 if you want to run it locally, and any external IP-address if you want to run it on a server.
      
      - GRAYLOG_ELASTICSEARCH_HOSTS=https://opensearch:9200
 
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog

    # Links MongoDB with OpenSearch.
    links:
      - mongo:mongodb
      - opensearch
    restart: always

    #Doesn't work without MongoDB and OpenSearch.
    depends_on:
      - mongo
      - opensearch
    ports:
      - 5044:5044/udp       # Beats UDP
      - 5044:5044/tcp        # Beats TCP
      - 9000:9000              # Graylog web interface and REST API
      - 1514:1514/udp      # Syslog UDP
      - 5555:5555/tcp       # Raw/Plaintext TCP input
networks:
    graylog:
      driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
```

After disabling HTTPS for OpenSearch, I also tried setting the `GRAYLOG_ELASTICSEARCH_HOSTS` without https (so just http) - doesn't work.

**Comment by janheise** [comment]
@AnonymousWP add `hostname: "opensearch"` to your opensearch section

**Comment by janheise** [comment]
also, I never used one of these in my docker files before:
`      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
` you might want to remove those, also do your logs show that opensearch comes up correctly? you could try opening port 9200, too.

**Comment by AnonymousWP** [comment]
Hmm, unfortunately this also doesn't seem to help. My current Docker Compose file:

```
# Image versions of the containers have to be manually edited once a new version is available

version: '3.7'
services:

  mongo:
    image: mongo:6.0.3
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.3.0

     # Stores OpenSearch data in this directory/path. Comes in handy when updating OpenSearch, so that data is retained.
    volumes:
      - es_data:/usr/share/opensearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g" # `Xms` specifies the initial memory allocation pool. `Xmx` specifies the maximum allocation pool for the Java Virtual Machine (JVM). "m" and "g" obviously stand for MB and GB.
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - "hostname:opensearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog
    restart: always

  graylog:
    image: graylog/graylog:5.0.0
    volumes:
      - graylog_data:/usr/share/graylog/data # Stores Graylog data in this directory/path. Comes in handy when updating Graylog, so that data is retained.
    environment:
      - GRAYLOG_PASSWORD_SECRET=<bla>

      - GRAYLOG_ROOT_PASSWORD_SHA2=<bla> # You can generate the SHA256-hash of your password with `echo -n <password> | sha256sum`

      - GRAYLOG_HTTP_EXTERNAL_URI=<bla> # You can change the IP-address to 127.0.0.1 if you want to run it locally, and any external IP-address if you want to run it on a server.

      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    # Sets the correct timezone within Graylog
      - TZ=Europe/Amsterdam
      - GRAYLOG_TIMEZONE=Europe/Amsterdam
      - GRAYLOG_ROOT_TIMEZONE=Europe/Amsterdam
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    ports:
    - 9200:9200/tcp

    # Links MongoDB with OpenSearch.
    links:
      - mongo:mongodb
      - opensearch
    restart: always

    #Doesn't work without MongoDB and OpenSearch.
    depends_on:
      - mongo
      - opensearch
    ports:
      - 5044:5044/udp       # Beats UDP
      - 5044:5044/tcp       # Beats TCP
      - 9000:9000           # Graylog web interface and REST API
      - 1514:1514/udp       # Syslog UDP
      - 5555:5555/tcp       # Raw/Plaintext TCP input
networks:
    graylog:
      driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
```

If you feel like https://github.com/Graylog2/docker-compose/issues/19 is a better place and more appropiate: let's continue there.
