### ISSUE TITLE
if start graylog,the opensearch node's io read become high

### ISSUE THREAD

**Issue by wyfaq** [Graylog2/graylog2-server#17715]
## Possible Solution
Which parameter causes graylog's read request for opensearch to be too high?
 

## Steps to Reproduce (for bugs)

1. shutdown graylog cluster
2. the opensearch read ok,
3. start then graylog cluster
4. the opensearch read very high, about 250MB/S，then write become very slow。Both reading and writing speeds reach the disk bottleneck.
## Your Environment

* Graylog Version:graylog 5.2.2+8eab621 *4
* Java Version: open jdk17
* OpenSearch Version: 2.11 
* MongoDB Version: 6.0.3
* Operating System: centos 7.9 
* Browser version: chrome 119.0.6045.199
* opensearch 2.11 *5
- indices * 131
- shard of indice： 4 
- Replicas of indice: 1
- indices capacity is ： 270GB

![image](https://github.com/Graylog2/graylog2-server/assets/8733527/3c2086d7-3af6-48c9-a1af-430445a507b4)
![image](https://github.com/Graylog2/graylog2-server/assets/8733527/48931472-2629-440e-8ebe-4dadb89d9187)

## graylog and opensearch config:
```yaml
cluster.name: graylog5_opensearch
node.name: ng-opensearch2
path.data: /opt/opensearch/data
path.logs: /var/log/opensearch
path.repo: ["/opt/opensearch/repo"]
network.host: 192.168.208.12
http.port: 9200
bootstrap.memory_lock: true
discovery.seed_hosts: ["ng-opensearch1","ng-opensearch2","ng-opensearch3","ng-opensearch4","ng-opensearch5"]
node.roles: [data,cluster_manager]
cluster.max_shards_per_node: 20000
cluster.routing.allocation.disk.watermark.low: 50gb
cluster.routing.allocation.disk.watermark.high: 30gb
cluster.routing.allocation.disk.watermark.flood_stage: 10gb
http.compression: true
plugins.security.allow_default_init_securityindex: true
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.ssl.transport.pemcert_filepath: ng-opensearch2.pem
plugins.security.ssl.transport.pemkey_filepath: ng-opensearch2.key
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: ng-opensearch2_http.pem
plugins.security.ssl.http.pemkey_filepath: ng-opensearch2_http.key
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.nodes_dn:
- CN=ng-opensearch1.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
- CN=ng-opensearch2.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
- CN=ng-opensearch3.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
- CN=ng-opensearch4.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
- CN=ng-opensearch5.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
plugins.security.authcz.admin_dn:
- CN=admin.aaa.com,OU=Ops,O=aaa.com\, Inc.,DC=aaa.com
http.max_initial_line_length: 128k
http.max_header_size: 64kb
http.max_content_length: 2147483647b
thread_pool:
    write:
        size: 5
        queue_size: 1000
action.auto_create_index: false
```

```yaml
# cat /etc/graylog/server/server.conf
is_leader = true
node_id_file = /etc/graylog/server/node-id
password_secret = xxxx
root_password_sha2 = xxxxxx
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 0.0.0.0:9000
stream_aware_field_types=false
elasticsearch_cluster_name = graylog5_opensearch 
elasticsearch_hosts = https://es:xxxxx@ng-opensearch2.aaa.com:9200,https://es:xxxxx@ng-opensearch1.aaa.com:9200,https://es:xxxx@ng-opensearch3.aaa.com:9200
elasticsearch_connect_timeout = 10s
elasticsearch_socket_timeout = 60s
elasticsearch_max_total_connections = 200
elasticsearch_max_total_connections_per_route = 20
elasticsearch_max_retries = 2
elasticsearch_analyzer = standard
elasticsearch_shards = 4
elasticsearch_replicas = 1
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_size_per_index = 53687091200
disabled_retention_strategies = none
allow_leading_wildcard_searches = false
allow_highlighting = false
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 8
outputbuffer_processors = 8
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 8
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /opt/graylog/journal
message_journal_max_age = 12h
message_journal_max_size = 2gb
message_journal_flush_age = 1m
message_journal_flush_interval = 1000000
message_journal_segment_age = 1h
message_journal_segment_size = 100mb
lb_recognition_period_seconds = 5
mongodb_uri = mongodb://graylog5:aaa@mongodbgraylog1-1.aaa.com:29017,mongodbgraylog1-2.aaa.com:29017/graylog5?replicaSet=gl
mongodb_max_connections = 1000
root_timezone = Asia/Shanghai
```
