### ISSUE TITLE
Incorrect Docker Compose format in docs

### ISSUE THREAD

**Issue by thatstatsguy** [Graylog2/graylog2-server#19717]
## Incorrect Docker Compose format in docs

I was looking at how to set up graylog to persist data 

https://go2docs.graylog.org/5-2/downloading_and_installing_graylog/docker_installation.htm

Currently the docker compose formatting is a incorrect - if someone can point me to the repo where the docs are stored I'm happy to update them.

**Comment by bernd** [comment]
@thatstatsguy Thanks for the report! :pray:  We don't have a repository for the documentation. I will file an internal ticket for it.

**Comment by bernd** [comment]
Here are the fixed Docker Compose examples:

https://go2docs.graylog.org/5-2/downloading_and_installing_graylog/docker_installation.htm#Configuration

```yaml
version: '3'
services:
  mongo:
    image: "mongo:6.0.14"
    # Other settings [...]
  opensearch:
    image: "opensearchproject/opensearch:2.12.0"
    # Other settings [...]
  graylog:
    image: "graylog/graylog:5.2"
    # Other settings [...]
    environment:
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: smtp
      GRAYLOG_TRANSPORT_EMAIL_PORT: 25
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
```

https://go2docs.graylog.org/5-2/downloading_and_installing_graylog/docker_installation.htm#PersistingData
```yaml
version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:6.0.14
    volumes:
      - mongo_data:/data/db

  # OpenSearch: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    volumes:
      - os_data:/usr/share/opensearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:5.2
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - opensearch
    restart: always
    depends_on:
      - mongodb
      - opensearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

  # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
  volumes:
    mongo_data:
      driver: local
    os_data:
      driver: local
    graylog_data:
      driver: local
```

https://go2docs.graylog.org/5-2/downloading_and_installing_graylog/docker_installation.htm#KubernetesAutomaticMasterSelection

```yaml
env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
```
