### ISSUE TITLE
Metrics for gl_jvm_memory_total_max and gl_jvm_memory_non_heap_max show unlimited in 6.0 where they previously showed the configured max in 5.2

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#19820]
When using the [metrics exporter](https://go2docs.graylog.org/current/interacting_with_your_log_data/metrics.html#ExportviaPrometheusMetricExporting) for graylog, the behavior of the following metrics has changed between Graylog 5.2 and 6.0:

* `gl_jvm_memory_total_max`
* `gl_jvm_memory_non_heap_max`

In Graylog 5.2 these displayed the configured max value for JVM heap. In Graylog 6.0 they show `-1` or unlimited:

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/9a1f8398-77fe-494f-9af1-3bb9d3c2cac1)

Its not clear to me which of these is the correct value to return though.

## Steps to Reproduce (for bugs)

1. Configure metric exporting via `server.conf`

```yaml
prometheus_exporter_enabled = true
prometheus_exporter_bind_address = 0.0.0.0:9833
prometheus_exporter_mapping_file_path_custom = /usr/share/graylog-server/prometheus-exporter-mapping-custom.yml
```

Relevant metrics declared in `prometheus-exporter-mapping-custom.yml`

```
metric_mappings:
  - metric_name: "jvm_memory_total_max"
    match_pattern: "jvm.memory.total.max"
  - metric_name: "jvm_memory_non_heap_max"
    match_pattern: "jvm.memory.non-heap.max"
```

2. view metric via :9833

## Your Environment

* Graylog Version: 6.0.3
* Java Version: Bundled
* OpenSearch Version: 2.15.0
* MongoDB Version: 6.0.16
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 126.0.6478.127 (Official Build) (arm64)
