### ISSUE TITLE
Datanodes running under docker bridge networks can not join clusters across hosts

### ISSUE THREAD

**Issue by a-zombie** [Graylog2/graylog2-server#20970]
## Expected Behavior
All datanodes should be able to join a cluster regardless with any routeable docker network configuration.

## Current Behavior
OpenSearch publishes the internal docker network address of the node which is non-routeable to other cluster members. This is because docker creates a host file on all containers which maps the hostname to it's internal network address, it also runs an internal DNS server which contains the same information. Datanode sets `network.publish_host` to be the hostname of the container. OpenSearch when it attempts to resolve `network.publish_host` gets the local address from the host file (or docker internal DNS server) and adds it to the publish list.
Example:
```
2024-11-15T16:44:14.489Z INFO  [OpensearchProcessImpl] [2024-11-15T16:44:14,489][INFO ][o.o.t.TransportService   ] [datanode2.gltest.internal] publish_address {datanode2.gltest.internal/172.18.0.2:9300}, bound_addresses {[::]:9300}
```
The address `172.18.0.2` is on an internal docker bridge network. Externally it resolves to a routeable address.

Host file:
```
$ docker exec -it datanode-datanode-1 cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.2      datanode2.gltest.internal datanode2
```

External resolution:
```
$ host datanode2.gltest.internal
datanode2.gltest.internal has address 10.100.100.93
```

Generated configuration (only the networky bits):
```
$ docker exec -it datanode-datanode-1 cat /var/lib/graylog-datanode/opensearch/config/opense
arch/opensearch.yml
---
network.host: "0.0.0.0"
http.port: "9200"
transport.port: "9300"
cluster.name: "datanode-cluster"
node.name: "datanode2.gltest.internal"
cluster.initial_cluster_manager_nodes: "datanode2.gltest.internal,datanode1.gltest.internal"
network.bind_host: "0.0.0.0"
network.publish_host: "datanode2.gltest.internal"
```
## Possible Solution
Allow setting `network.publish_host` independently of the host name. This occurs when the hostname matches `network.publish_host` in a docker bridge network.

Example:
Hostname: `datanode.example.org` - Publish_Host: `datanode.example.org` - Local Docker IP is published by OpenSearch
Hostname: `datanode` - Publish_Host: `datanode.example.org` - IP resolved normally for `datanode.example.org` and would be published by OpenSearch.

I can't test changing `network.publish_host` since datanode sets it automatically but I can show the DNS resolution changes.
Hostname: `datanode2`
```
$ docker exec -it datanode-datanode-1 getent hosts datanode2
172.18.0.2      datanode2
$ docker exec -it datanode-datanode-1 getent hosts datanode2.gltest.internal
10.100.100.93   datanode2.gltest.internal
```

## Steps to Reproduce (for bugs)
You need two hosts that can communicate across the network.

Host 1 - Graylog, MongoDB and Datanode
Host 2 - Docker running datanode.
DNS or `/etc/hosts` on all hosts to resolve the intended nodes (in my case hosts file and datanode1.gltest.internal and datanode2.gltest.internal)

Example compose config:
```
services:
  datanode:
    image: "graylog/graylog-datanode:6.1"
    hostname: "datanode2.gltest.internal"
    environment:
      GRAYLOG_DATANODE_NODE_NAME: "datanode2.gltest.internal"
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "_your_root_password_in_sha256"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodbhost:27017/graylog"
      GRAYLOG_DATANODE_OPENSEARCH_DATA_LOCATION: "/var/lib/opensearch"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - datanode
    volumes:
      - "./datanode_config:/var/lib/graylog-datanode"
      - "./opensearch_data:/var/lib/opensearch"
    restart: "on-failure"

networks:
  datanode:
    driver: "bridge"
```

1. Start Host 1 and all services, make sure that datanode initializes and Graylog is accessible.
2. Start Host 2 and bring up docker datanode.
3. Cluster will never form, errors will occurs as the datanodes will attempt to connect to the docker internal non-routable IP.
```
2024-11-15T17:07:07.929Z INFO  [OpensearchProcessImpl] [2024-11-15T17:07:07,926][WARN ][o.o.d.HandshakingTransportAddressConnector] [datanode1.gltest.internal] [connectToRemoteMasterNode[10.100.100.93:9300]] completed handshake with [{datanode2.gltest.internal}{qzR5I81ZSiiNCC5FM8fB7Q}{SktF0u99QeiyhVDFcvOq7A}{datanode2.gltest.internal}{172.18.0.2:9300}{dimrs}{shard_indexing_pressure_enabled=true}] but followup connection failed
2024-11-15T17:07:07.930Z INFO  [OpensearchProcessImpl] org.opensearch.transport.ConnectTransportException: [datanode2.gltest.internal][172.18.0.2:9300] connect_exception
2024-11-15T17:07:07.932Z INFO  [OpensearchProcessImpl] Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: datanode2.gltest.internal/172.18.0.2:9300
```

## Context
Docker bridges provide service isolation from the wider network, this is the default configuration when you do not specify a network type in docker compose. I would image the same issue could happen in Kubernetes or behind other load balancers, proxies, NAT, etc.

## Your Environment
Two brand new for testing only Ubuntu 22.04 servers running on Hyper-V.

* Graylog Version: 6.1.2 (docker)
* Java Version: Embedded
* Datanode Version: 6.1.2 (docker)
* MongoDB Version: 7.0.15 (docker)
* Operating System: Ubuntu 22.04
* Browser version: Firefox 132.0.2

**Comment by a-zombie** [comment]
As an update. This may also apply to kubernetes deployments but a workaround is available.
**Please note I have surface knowledge of kubernetes networking and there may be other ways to work around this**

Workaround: Set the Service `spec.clusterIP` to `"None"` this creates a headless service which registers the DNS to the pod IP instead of a Cluster IP. **I do not know if this is acceptable in production**

Consider the following two datanodes `datanode2` with the workaround applied and `datanode3` with a default "ClusterIP" service type.
```
root@graylog-0:/usr/share/graylog# host datanode2
datanode2.default.svc.cluster.local has address 10.42.1.5
root@graylog-0:/usr/share/graylog# host datanode3
datanode3.default.svc.cluster.local has address 10.43.16.37
```
Performing name resolution from another container shows the following DNS resolution.
`datanode2` has an address of `10.42.1.5` (the pod IP)
`datanode3` has an address of `10.43.16.37` (a Cluster IP, it's pod IP is `10.42.1.8`)

Looking at what these nodes are bound to and what they publish when a node joins a cluster.

datanode2:
```
root@k3s-test1:~# kubectl logs datanode2 | grep -Ei 'bound|publish'
2024-11-22T21:40:12.018Z INFO  [NetworkListener] Started listener bound to [0.0.0.0:8999]
2024-11-22T21:40:27.887Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:27,886][INFO ][o.o.t.TransportService   ] [datanode2] publish_address {datanode2/10.42.1.5:9300}, bound_addresses {[::]:9300}
2024-11-22T21:40:28.049Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:28,049][INFO ][o.o.b.BootstrapChecks    ] [datanode2] bound or publishing to a non-loopback address, enforcing bootstrap checks
2024-11-22T21:40:29.306Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:29,304][INFO ][o.o.h.AbstractHttpServerTransport] [datanode2] publish_address {datanode2/10.42.1.5:9200}, bound_addresses {[::]:9200}
```
datanode3:
```
root@k3s-test1:~# kubectl logs datanode3 | grep -Ei 'bound|publish'
2024-11-22T21:39:58.070Z INFO  [NetworkListener] Started listener bound to [0.0.0.0:8999]
2024-11-22T21:40:19.767Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:19,767][INFO ][o.o.t.TransportService   ] [datanode3] publish_address {datanode3/10.42.1.8:9300}, bound_addresses {[::]:9300}
2024-11-22T21:40:20.064Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:20,062][INFO ][o.o.b.BootstrapChecks    ] [datanode3] bound or publishing to a non-loopback address, enforcing bootstrap checks
2024-11-22T21:40:22.195Z INFO  [OpensearchProcessImpl] [2024-11-22T21:40:22,189][INFO ][o.o.h.AbstractHttpServerTransport] [datanode3] publish_address {datanode3/10.42.1.8:9200}, bound_addresses {[::]:9200}
```
The following is published.
`datanode2` publishes `{datanode2/10.42.1.5:9300}` - matches DNS
`datanode3` publishes `{datanode3/10.42.1.8:9200}` - does not match DNS (matches pod IP)

Node `datanode3` may have network path issues because the DNS resolution does not match the cluster published IP.

**Comment by moesterheld** [comment]
I think using the config parameter `bind_address` would resolve the issue.

Using
```
    environment:
      GRAYLOG_DATANODE_NODE_NAME: "mydatanode.external"
      GRAYLOG_DATANODE_BIND_ADDRESS: "mydatanode.external"
```
will result in a generated `opensearch.yml` with
```
node.name: "mydatanode.external"
cluster.initial_cluster_manager_nodes: "mydatanode.external"
network.bind_host: "mydatanode.external"
network.publish_host: "mydatanode.external" 
```

Notice that the `node_name` also needs to be adjusted for this to work right now. I have to look into a way if these can be set independently for it to work

**Comment by a-zombie** [comment]
This results in the same issue. Using my same setup as above with the changes you suggest.

If you set the following (under the appropriate sections in docker-compose.yml):
```
hostname: "datanode2"
GRAYLOG_DATANODE_NODE_NAME: "datanode2.gltest.internal"
GRAYLOG_DATANODE_BIND_ADDRESS: "datanode2.gltest.internal"
```

Then OpenSearch produces the following error (inside DataNode).
```
2025-03-14T15:54:22.684Z INFO  [OpensearchProcessImpl] org.opensearch.bootstrap.StartupException: BindTransportException[Failed to bind to 10.100.100.93:9300]; nested: BindException[Cannot assign requested address];
```

This is because the container IP is on a bridge network (in my test `"IPAddress": "172.18.0.2"`) and cannot bind to the host IP.

If you change the hostname to the following:
```
hostname: "datanode2.gltest.internal"
GRAYLOG_DATANODE_NODE_NAME: "datanode2.gltest.internal"
GRAYLOG_DATANODE_BIND_ADDRESS: "datanode2.gltest.internal"
```

Then the same behaviour as above is performed.
```
2025-03-14T16:01:10.428Z INFO  [OpensearchProcessImpl] [2025-03-14T16:01:10,428][INFO ][o.o.t.TransportService   ] [datanode2.gltest.internal] publish_address {datanode2.gltest.internal/172.18.0.2:9300}, bound_addresses {172.18.0.2:9300}
```

Docker's internal networking is a bridge and does automatic DNS resolution based on the container `hostname` attribute. So if `hostname` matches the `GRAYLOG_DATANODE_BIND_ADDRESS` variable it publishes the internal non-routable bridge IP to the OpenSearch cluster.

In OpenSearch `network.publish_host` is the variable that can be set in OpenSearch which does not have to match `network.bind_host` and is what is broadcast as "here is now to find this node on the network".

The _Possible Solution_ from the original issue would likely solve this.

The following possible config
```
hostname: "datanode2"
GRAYLOG_DATANODE_NODE_NAME: "datanode2.gltest.internal"
GRAYLOG_DATANODE_BIND_ADDRESS: "0.0.0.0" // this would be the default
GRAYLOG_DATANODE_PUBLISH_ADDRESS: "datanode2.gltest.internal"
```

Should result in the following `opensearch.yml`.
```
node.name: "datanode2.gltest.internal"
cluster.initial_cluster_manager_nodes: "datanode2.gltest.internal datanode1.gltest.internal" // this only occurs with 2+ nodes spread across hosts (aka not managed by the same docker daemon).
network.bind_address: "0.0.0.0"
network.publish_host: "datanode2.gltest.internal"
```

**Comment by williamtrelawny** [comment]
@a-zombie Regarding your k8s config (can't speak for Docker)- I think for Data Node/Opensearch you HAVE to use a headless service because traffic needs to flow to each specific node, not round-robined via a ClusterIP. Esp since Opensearch already does its own load balancing in a sense, just like with Linux installs (we don't put LB's in front of Osearch in any context for this reason afaik)

**Comment by TheBolshe** [comment]
Hello, i'm trying to setup a graylog cluster across 3 vms and I'm using docker compose with a mongodb, datanode and graylog container on each machine.
I'm just using docker compose, no k8 or docker swarm.

Here's the docker compose for my main machine :
```yaml
services:
  mongodb1:
    image: mongo:8
    hostname: mongodb1
    container_name: mongodb1
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d
      - ./mongodb/init-replset.js:/init-replset.js
    ports:
      - "27017:27017"
    networks:
      - graylog
    restart: on-failure
    healthcheck:
      test: mongosh --quiet --eval "rs.status().ok"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  datanode1:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:7.0}"
    hostname: graylog-data-1
    container_name: datanode1
    depends_on:
      mongodb1:
        condition: service_healthy
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://graylog-1:27017,graylog-2:27017,graylog-3:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - ./graylog/datanode:/var/lib/graylog-datanode
    networks:
      - graylog
    restart: on-failure

  graylog1:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:7.0}"
    container_name: "graylog1"
    depends_on:
      mongodb1:
        condition: service_healthy
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_IS_LEADER: "true"
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://graylog-1:27017,graylog-2:27017,graylog-3:27017/graylog"
    ports:
      - "9000:9000"        # Graylog web interface and REST API
      - "1514:1514"        # Syslog TCP
      - "1514:1514/udp"    # Syslog UDP
     # - "127.0.0.1:12201:12201"      # GELF TCP
     # - "127.0.0.1:12201:12201/udp"  # GELF UDP
    volumes:
      # IMPORTANT: bind mounts (e.g., "./data:/usr/share/graylog/data") currently
      # don't work correctly. You have to use volume mounts.
      # See: https://github.com/Graylog2/docker-compose/issues/99#issuecomment-3800898829
      - "graylog-data-01:/usr/share/graylog/data"
      - "graylog-journal-01:/usr/share/graylog/data/journal"
    networks:
      - graylog
    restart: on-failure

networks:
  graylog:
    name: graylog
    driver: bridge

volumes:
  graylog-data-01:
  graylog-journal-01:
```

I'm currently stuck at the preflight configuration when provisioning the certificates because the datanodes seem to use their internal docker network ip addresses. 

```
datanode1  | 2026-04-20T09:06:43.064Z INFO  [OpensearchProcessImpl] [2026-04-20T09:06:43,064][WARN ][o.o.d.HandshakingTransportAddressConnector] [graylog-data-1] [connectToRemoteMasterNode[REDACTED:9300]] completed handshake with [{graylog-data-3}{Iym-wHHUTKiK3UBDgmaBpA}{ikJr_L3NSw2-e4H3zg9lPw}{graylog-data-3}{172.18.0.4:9300}{dimr}{shard_indexing_pressure_enabled=true}] but followup connection failed
datanode1  | 2026-04-20T09:06:43.064Z INFO  [OpensearchProcessImpl] org.opensearch.transport.ConnectTransportException: [graylog-data-3][172.18.0.4:9300] connect_exception
datanode1  | 2026-04-20T09:06:43.064Z INFO  [OpensearchProcessImpl]     at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1078) ~[opensearch-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:43.064Z INFO  [OpensearchProcessImpl]     at org.opensearch.core.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:217) ~[opensearch-core-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:43.064Z INFO  [OpensearchProcessImpl]     at org.opensearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:57) ~[opensearch-common-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at org.opensearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:72) ~[opensearch-common-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at org.opensearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:83) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:642) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:131) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:326) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:342) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:697) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:660) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[?:?]
datanode1  | 2026-04-20T09:06:43.065Z INFO  [OpensearchProcessImpl]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl] Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: graylog-data-3/172.18.0.4:9300
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl] Caused by: java.net.ConnectException: Connection refused
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339) ~[?:?]
datanode1  | 2026-04-20T09:06:43.066Z INFO  [OpensearchProcessImpl]     ... 7 more
datanode1  | 2026-04-20T09:06:43.157Z INFO  [OpensearchProcessImpl] [2026-04-20T09:06:43,157][INFO ][o.o.s.c.ConfigurationRepository] [graylog-data-1] Wait for cluster to be available ...
datanode1  | 2026-04-20T09:06:44.053Z INFO  [OpensearchProcessImpl] [2026-04-20T09:06:44,052][WARN ][o.o.d.HandshakingTransportAddressConnector] [graylog-data-1] [connectToRemoteMasterNode[REDACTED:9300]] completed handshake with [{graylog-data-3}{Iym-wHHUTKiK3UBDgmaBpA}{ikJr_L3NSw2-e4H3zg9lPw}{graylog-data-3}{172.18.0.4:9300}{dimr}{shard_indexing_pressure_enabled=true}] but followup connection failed
datanode1  | 2026-04-20T09:06:44.053Z INFO  [OpensearchProcessImpl] org.opensearch.transport.ConnectTransportException: [graylog-data-3][172.18.0.4:9300] connect_exception
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1078) ~[opensearch-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at org.opensearch.core.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:217) ~[opensearch-core-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at org.opensearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:57) ~[opensearch-common-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at org.opensearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:72) ~[opensearch-common-2.19.3.jar:2.19.3]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at org.opensearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:83) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:642) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:131) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:326) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:342) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:697) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:660) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl] Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: graylog-data-3/172.18.0.4:9300
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl] Caused by: java.net.ConnectException: Connection refused
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339) ~[?:?]
datanode1  | 2026-04-20T09:06:44.054Z INFO  [OpensearchProcessImpl]     ... 7 more
```

All 3 machines have dhcp records that allow them to be accessed by their docker hostnames.

Is there a workaround for this issue yet ? If not, should i abandon trying to deploy graylog that way ?
