### ISSUE TITLE
Stability Issues Running In Kubernetes

### ISSUE THREAD

**Issue by GEverding** [Graylog2/graylog2-server#2236]
### Problem description
Hi, I've been running graylog2 1.3.x in Kubernetes for the 4+ months with mixed results. When I run a single graylog-server container everything is fine and stable. However, when I run 2 graylog-servers i experience daily outages because the webinterface cannot connect to the configured servers. I have a kubernetes service for each graylog server in the cluster which gives me 2 dns records the look like this: `graylog-server-1.default`, `graylog-server-x.default`. Can anyone help me debug these stability issues? 

### Environment

* Graylog Version: 1.3.x
* Elasticsearch Version: 1.7.x
* MongoDB Version:
* Operating System: Ubuntu
* Browser version:

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by daikaixian** [comment]
@GEverding  hello, i am trying to deploy graylog2 in my k8s cluster.
But I don't know hoe to write the .yaml file.
Because there are not enough information i can find fron google to do so .
So  may u help you ? show me your .yaml  file for deploy graylog2 in k8s.
Thx!

**Comment by GEverding** [comment]
Yeah. They are a little old and I had to build custom images. Not sure if you'd still need to do that.

So I split it out into 2 rc's. One for the server and one for web. The first one is the server and the second is the web rc. I also have some tempting in there to make deployments easier. 
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: graylog-server-rc-1
  labels:
    component: graylog
    role: server
    node: node1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: graylog
        role: server
        node: node1
    spec:
      containers:
      - name: graylog-server-1
        image: graylog-server:latest
        ports:
        - containerPort: {{ graylog.container_port }} 
          name: udp
          protocol: UDP
        - containerPort: {{ graylog.container_port }}
          name: tcp
          protocol: TCP
        - containerPort: {{ graylog.api_port }}
          name: graylog-api
          protocol: TCP
        volumeMounts:
        - mountPath: /var/opt/graylog/data
          name: data
        - mountPath: /var/log/graylog
          name: data
        - mountPath: /opt/graylog/plugin
          name: data
        env:
        - name: GRAYLOG2_IS_MASTER
          value: "true"
        - name: GRAYLOG2_NODE_ID_FILE
          value: "/opt/graylog-node-id"
      volumes:
      - name: data
        gcePersistentDisk:
          pdName: graylog-data-1
          fsType: ext4        #
```
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: graylog-web-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: graylog
        role: web
    spec:
      containers:
      - name: graylog-web
        image: graylog-web:{{ graylog.web_image_tag }}
        ports:
        - containerPort: {{graylog.http_port }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/opt/graylog/data
          name: data
        - mountPath: /var/log/graylog
          name: data
        - mountPath: /opt/graylog/plugin
          name: data
      volumes:
      - name: data
        gcePersistentDisk:
          pdName: graylog-web-1
          fsType: ext4        #
```

The biggest gotcha I had was the "undocumented" environment variables that graylog actually supports. If you do a little searching in the code base you'll find them. Let me know if you have specific questions I can answer.
