### ISSUE TITLE
Data Node certificates should contain DNS Short Names in SAN

### ISSUE THREAD

**Issue by williamtrelawny** [Graylog2/graylog2-server#22598]
Data Node certificates should include both the DNS short name and FQDN of nodes so they can properly represent them in all deployment contexts. I've only ever had an issue with this in a Kubernetes environment, but I suppose it would apply to any environments heavily reliant on DNS for connectivity and who may have more complicated DNS infrastructure.

## What?
Currently, the certificate generated by Data Node contains only the FQDN and not the short name (e.g. `datanode-0.example.com` and not `datanode-0`). Whereas in K8s pod-to-pod communication via a `Service`, it does so using Pod FQDNs. As it happens, the Opensearch `publish.uri` is set to the FQDN automatically.

### Workaround
I can get this to work properly only when I set the `node.name` in `opensearch.yml` to the Pod's FQDN to match the `publish.address`. So perhaps this isn't a k8s-specific issue but a broader one where the `node.name` and `publish.address` don't match.

An excerpt from my StatefulSet config to enable this workaround:
```
spec:
  template:
    spec:
      containers:
      - name: datanode
        env:
        - name: POD_NAME # <-- Set env to capture the pod's name stored in pod metadata, for use below
          valueFrom:
            fieldRef:
            fieldPath: metadata.name
        - name: GRAYLOG_DATANODE_NODE_NAME
          value: $(POD_NAME).datanode-headless.graylog.svc.cluster.local
```

## Why?
Does not allow a Data Node cluster to bootstrap itself in a k8s environment or likely other multi-container environments.

Possibly related: https://github.com/Graylog2/graylog2-server/issues/20970

## Your Environment

* Graylog Version: 6.2
* OpenSearch Version: 2.15
* Operating System: Kubernetes 1.32
