### ISSUE TITLE
Docker container starts elasticsearch by default

### ISSUE THREAD

**Issue by wrouesnel** [Graylog2/graylog2-server#2457]
### Problem description
When starting the graylog docker container, the instructions provided imply that it does not start an ES node by default (due to the need to start an ES container alongside it). This appears to be invalid - the configuration file defaults to starting an ES instance embedded in the container, which can join a cluster as a node that takes on data.

This can lead to some surprising first-use behavior in testing.

### Steps to reproduce the problem

1. Launch a graylog cluster following the instructions:
```
some-mongo:
  image: "mongo:3"
some-elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
graylog:
  image: graylog2/server
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
  links:
    - some-mongo:mongo
    - some-elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
```
2. Observer that elasticsearch instance is in a cluster of 2 with the graylog container.

### Environment

* Graylog Version: latest
* Elasticsearch Version: 2
* MongoDB Version: 3
* Operating System: Linux (Docker)
* Browser version: Not relevant
