### ISSUE TITLE
Elasticsearch cluster unavailable on graylog2/allinone Docker image

### ISSUE THREAD

**Issue by averri** [Graylog2/graylog2-server#2524]
### Problem description

![image](https://cloud.githubusercontent.com/assets/1898447/17101074/6087312e-526a-11e6-805f-a2bc9d2683aa.png)

### Steps to reproduce the problem

Run Docker image:
```
docker run -t -p 9000:9000 -p 12201:12201 -d graylog2/allinone
```

**Comment by mariussturm** [comment]
The `allinone` image is deprecated please use the `server` image with docker-compose to run Elasticsearch. https://hub.docker.com/r/graylog2/server/

**Comment by averri** [comment]
Hi @mariussturm , thank you for the information.

Now I am using docker-compose:

```
mongo:
  image: "mongo:3"
  volumes:
    - /data/graylog/data/mongo:/data/db
elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
  volumes:
    - /data/graylog/data/elasticsearch:/usr/share/elasticsearch/data
graylog:
  image: graylog2/server:2.0.1-1
  volumes:
    - /data/graylog/data/journal:/usr/share/graylog/data/journal
    - /data/graylog/config:/usr/share/graylog/data/config
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900

  links:
    - mongo:mongo
    - elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
```

Downloaded config files inside `/data/graylog/config` as: 

```
wget https://raw.githubusercontent.com/Graylog2/graylog2-images/2.0/docker/config/graylog.conf
wget https://raw.githubusercontent.com/Graylog2/graylog2-images/2.0/docker/config/log4j2.xml
```
And getting the following error when accessing Graylog:

![image](https://cloud.githubusercontent.com/assets/1898447/17102418/6764bb0e-5271-11e6-9d85-dafe3e4f50f3.png)
