### ISSUE TITLE
Graylog does not show messages

### ISSUE THREAD

**Issue by averri** [Graylog2/graylog2-server#2557]
### Problem description
Graylog does not show any message. I can see incoming messages in the global input:

![image](https://cloud.githubusercontent.com/assets/1898447/17179740/2c0a0828-5412-11e6-98fc-950b73a926bf.png)

... but it does not show the messages: 

![image](https://cloud.githubusercontent.com/assets/1898447/17179786/4cd6c942-5412-11e6-971b-524ff8a16555.png)

### Steps to reproduce the problem
1. Create a new input for SYSLOG TCP.
2. Send messages to SYSLOG TCP port.
3. Click on the button `Show received messages`

### Environment
I am using the following docker-compose:

```
version: '2'
services:
  mongo:
    image: mongo:3
    volumes:
      - /data/graylog/data/mongo:/data/db
  elasticsearch:
    image: elasticsearch:2
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /data/graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.0.1-1
    volumes:
      - /data/graylog/data/journal:/usr/share/graylog/data/journal
      - /data/graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_REST_TRANSPORT_URI: http://myserver:12900
    ports:
      - 9000:9000
      - 12900:12900
      - 1514:1514
      - 12200:12200
      - 12201:12201
```

**Comment by kroepke** [comment]
@averri Can you please check the System/Indices page if the messages are in elasticsearch?
If they are, this typically is an issue with timezones and/or times in the future or well outside the search window

**Comment by averri** [comment]
Hi @kroepke, the messages are in elasticsearch, please see bellow. Indeed, the messages are originated from a server with a different timezone, but I have set an appropriate filter time.

![image](https://cloud.githubusercontent.com/assets/1898447/17181381/d9a01df6-5417-11e6-977a-2a80099d1e24.png)

Even setting the filter for last 30 days, there are no messages:

![image](https://cloud.githubusercontent.com/assets/1898447/17181531/637624bc-5418-11e6-9c2e-5525f6c9c7de.png)

**Comment by averri** [comment]
Hi @kroepke, I have set the input to RAW TCP, and have tested it with Telnet, it's working. I also tested using [Logspout](https://github.com/gliderlabs/logspout) sending logs to Graylog with success. 

So, in summary:

1) Using SYSLOG TCP input and Logspout **does not** show the messages.

```
docker run --name="log_syslog_tcp" \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    gliderlabs/logspout \
    syslog+tcp://myserver:1514
```

2) Using RAW TCP input and Logspout does show the messages.

```
docker run --name="log_raw_tcp" \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    gliderlabs/logspout \
    tcp://myserver:1514
```

**Comment by averri** [comment]
Here is another example to reproduce the issue.

1) Create a new SYSLOG TCP input on port 1514:

![image](https://cloud.githubusercontent.com/assets/1898447/17185900/e1c6cc24-542a-11e6-9428-88d422b08ee9.png)

2) Send a message using Docker SYSLOG driver:

```
docker run --log-driver=syslog \
--log-opt syslog-address=tcp://graylog-server:1514  \
alpine echo "hello"
```

3) Click on **Show received messages**:

![image](https://cloud.githubusercontent.com/assets/1898447/17185973/32feaa80-542b-11e6-822d-ba0daa6f9dd2.png)

**Comment by joschi** [comment]
@averri Please extend the search time range into the future (using an absolute time range).
If your messages have the wrong timestamp (or no time zone information at all, which makes Graylog fall back to assume UTC), they can have a timestamp some hours in the future.

**Comment by averri** [comment]
@kroepke and @joschi, thank you very much. As I mentioned before, the messages come from a server on a different timezone. But now I have changed the filter to absolute, and it is working fine. By the way, I don't know why the filter **Search in all messages** does not show the messages.

In summary:

1) Does not show the messages

![image](https://cloud.githubusercontent.com/assets/1898447/17206698/dcb33d98-54a8-11e6-98ad-2ba3b1941881.png)

2) Show the messages:

![image](https://cloud.githubusercontent.com/assets/1898447/17206708/f50be4f8-54a8-11e6-91d3-59f16a14c6e4.png)

**Comment by joschi** [comment]
@averri "Search in all messages" only looks from "now" and not from the future. We might change that in a subsequent release.

Since the cause of the problem has been found, I'll close this issue.

**Comment by averri** [comment]
@joschi, so that explains everything! Thank you.

**Comment by rompic** [comment]
had a similar problem on my test set up. thanks for the "look into the future" hint.

**Comment by fabriziocucci** [comment]
I'm experiencing the same issue and, in my case, I can see the message if I switch to absolute and I don't actually need to travel into the future (note my time, the timestamp of the messages and the time range).

ABSOLUTE
<img width="1433" alt="absolute" src="https://cloud.githubusercontent.com/assets/8156463/20644936/7e0af7ce-b441-11e6-95b6-131822f58197.png">

RELATIVE
<img width="1440" alt="relative" src="https://cloud.githubusercontent.com/assets/8156463/20644937/7e23c24a-b441-11e6-9111-20f403a51fb9.png">

I still don't understand what's wrong with my configuration. 

This is my docker-compose file:

```yaml
version: '2'
services:
  some-mongo:
    image: "mongo:3"
  some-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
```

This is my log4j2 configuration file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO" packages="org.graylog2.log4j2">
	<Appenders>
		<GELF name="gelfAppender" server="localhost" port="12201"></GELF>
	</Appenders>
	<Loggers>
		<Root level="debug">
                	<AppenderRef ref="gelfAppender" />
		</Root>
	</Loggers>
</Configuration>
```

As you can see, I'm using GELF UDP.
