### ISSUE TITLE
Include Collector-Sidecar Configurations in Content Pack

### ISSUE THREAD

**Issue by jensschulze** [Graylog2/graylog2-server#2642]
Feature Request
## Expected Behavior

For the sake of simplicity and consistency the configurations for the Graylog Collector Sidecar should be integrated into the Content Packs.
## Current Behavior

Whenever I spin up a new Graylog Server I have to configure the Graylog Collector Sidecar(s) manually, or have to fumble around with MongoDB.

**Comment by awilkins** [comment]
I'm doing this with the "uri" task in Ansible : 

```yaml
  - name: Create sidecar collector config
    register: apply
    uri:
      url: "http://localhost:9000/api/plugins/org.graylog.plugins.collector/configurations"
      method: POST
      body: "{{ lookup('file', 'collector-config.json') }}"
      body_format: "json"
      user: admin
      HEADER_Accept: "application/json"
      password: "{{ admin_pass }}"
      status_code: 200
    when: bundle.status == 404
    changed_when: yes
```
