### ISSUE TITLE
Can't bind GELF UDP input inside the graylog server docker container

### ISSUE THREAD

**Issue by sysadmin1337** [Graylog2/graylog2-server#2943]
## Expected Behavior

Successfully start the input.

## Current Behavior

Unable to start a graylog input inside the graylog server docker container. No error message shows up, the input just doesn't work/listen. Strangely a few log files from a client manage to get through but then it stops because I guess the input is not running/working.

## Possible Solution

Not sure, maybe conflicting with docker comopose port? But I guess it should be open for the container to receive any messages at all?

## Steps to Reproduce (for bugs)

1. Spin up a vagrant machine and change ip values in docker compose file below
2. docker-compose up -d
3. Login to graylog interface and add input with following information:
![selection_008](https://cloud.githubusercontent.com/assets/22659660/19309030/d1c13488-9082-11e6-8eef-f8741a2acece.png)

## Context

docker-compose.yml
```
version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:latest
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
      - /graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: xxx
      GRAYLOG_ROOT_PASSWORD_SHA2: xxx
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.x.x:9000/api/
      GRAYLOG_REST_TRANSPORT_URI: http://192.168.x.x:9000
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "5044:5044"
      - "5140/udp:5140/udp"
      - "12201/udp:12201/udp"
```

## Your Environment

* Graylog Version: `graylog2/server:latest`
* Elasticsearch Version: `elasticsearch:2`
* MongoDB Version: `mongo:3`
* Operating System: Ubuntu 16.04
* Browser version: Any
