### ISSUE TITLE
Docker compose installation results with ERROR StatusLogger File not found

### ISSUE THREAD

**Issue by matfiz** [Graylog2/graylog2-server#2996]
I have installed the graylog stack using docker-compose configuration recommended in the docs:

```
version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.0-3
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
      - /graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
```
After I `docker-compose up`, I see the graylog container exits with error:
`ERROR StatusLogger File not found in file system or classpath: /usr/share/graylog/data/config/log4j2.xml`

How can I generate this file? :)

## Expected Behavior
After starting the docker composer, there should be no errors.

## Current Behavior
After I `docker-compose up`, I see the graylog container exits with error:
`ERROR StatusLogger File not found in file system or classpath: /usr/share/graylog/data/config/log4j2.xml`

## Possible Solution

Generate/provide link to `log4j2.xml`?
