### ISSUE TITLE
No any errors in log, but just cannot access the web interface

### ISSUE THREAD

**Issue by lnshi** [Graylog2/graylog2-server#4022]
I configured
```
GRAYLOG_WEB_LISTEN_URI: http://0.0.0.0:9000/
GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:9000/api/
GRAYLOG_REST_TRANSPORT_URI: http://${GRAYLOG2_SERVER_HOSTNAME}:9000/api/
```
No any errors pop up in the logs, can successfully connect to the MongoDB servers and the elastic-search servers, just cannot access the web UI, keep  getting:
```
We are experiencing problems connecting to the Graylog server running on http://micro02.sgdev.vcube.com:9000/api/. Please verify that the server is healthy and working correctly.

You will be automatically redirected to the previous page once we can connect to the server.
```
```
Error message
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
Original Request
GET http://micro02.sgdev.vcube.com:9000/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```
With docker hub image: [graylog2/server:2.3.0-rc.2-2](https://hub.docker.com/r/graylog2/server/tags/)

**Comment by joschi** [comment]
@lnshi Please post your complete Docker configuration.

Is `http://micro02.sgdev.vcube.com:9000/api/` the correct URI of the Graylog REST API which is accessible by your web browser?

**Comment by lnshi** [comment]
@joschi  Yes, it is correct.

The whole docker configuration part for the graylog2_server:
```
graylog2_server:
  image: graylog2/server:2.3.0-rc.2-2
  hostname: graylog2_server
  environment:
    GRAYLOG_PASSWORD_SECRET: l4dIKl7ocXp1hw2IZdBOCGFwLjdKDsILYxjlGRxlkJvjYVY3sAaSarTZ05gyo4hCuAWXuydO3LGIo3F5WIOWr5gKyeH6F0Gp

    GRAYLOG_ROOT_USERNAME: leonard
    GRAYLOG_ROOT_PASSWORD_SHA2: c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646
    GRAYLOG_ROOT_EMAIL: leonard.shi@xxx.xx.xx
    GRAYLOG_ROOT_TIMEZONE: UTC

    GRAYLOG_WEB_LISTEN_URI: http://0.0.0.0:9000/
    GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:9000/api/
    GRAYLOG_REST_TRANSPORT_URI: http://${GRAYLOG2_SERVER_HOSTNAME}:9000/api/

    GRAYLOG_MONGODB_URI: mongodb://ip_x1:27017,ip_x2:27017/microservices_graylog
    
    GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch-server-0:9200,http://elasticsearch-server-1:9200,http://elasticsearch-server-2:9200
    GRAYLOG_ELASTICSEARCH_MAX_TOTAL_CONNECTIONS: 9
    GRAYLOG_ELASTICSEARCH_MAX_TOTAL_CONNECTIONS_PER_ROUTE: 3
    GRAYLOG_ELASTICSEARCH_MAX_RETRIES: 100
    GRAYLOG_ELASTICSEARCH_DISCOVERY_ENABLED: 'true'
  networks:
    - default
  ports:
    - '64999:9000'
  deploy:
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - node.hostname == ${GRAYLOG2_SERVER_HOSTNAME}
    restart_policy:
      condition: any
```
