### ISSUE TITLE
TCP Input messages "dropped" at high send volumes

### ISSUE THREAD

**Issue by Aenima4six2** [Graylog2/graylog2-server#4028]
When messages are sent at a rate (presumably too high for graylog to process), messages are dropped without any kind of client side errors occurring. Tests cases were performed on multiple dockerized instances of graylog server using the following test script: https://github.com/Aenima4six2/graylog-delivery-ratio

## Expected Behavior
Using a TCP input should guarantee any messages sent should be successfully delivered and processed or an error should occur at the client end. 

## Current Behavior
When high rate of messages are sent to Graylog server, the client is informed that all packets (thus messages) were received, however, the Graylog journal and Elasticsearch index show otherwise (IE: 10000 messages sent and 9800 in the journal).
<img width="1064" alt="screen shot 2017-07-21 at 11 15 08 am" src="https://user-images.githubusercontent.com/2087362/28474831-455d0b58-6e07-11e7-8a00-6e1ac282704d.png">

## Possible Solution
Possibly rate limit or throttle incoming TCP/UDP connections such that all can be processed in time without timeouts or dropped messages.

## Steps to Reproduce (for bugs)
1. docker compose up with the provided compose file (below).
<img width="754" alt="screen shot 2017-07-21 at 11 10 28 am" src="https://user-images.githubusercontent.com/2087362/28474373-b1b40042-6e05-11e7-85d5-5ecc886c61c9.png">
2. Ensure a TCP input has been created and started on the default GELF port (12201).
3. If using provided test script, clone or download python test script from repo above. Ensure python3 is installed and restore all dependencies with pip install -r requirements.txt
4. Send an onslaught of messages via TCP to graylog using a correlation id to count how many of the messages were received in the batch. If using the test script, use: 
`python3 test_delivery_ratio.py -t 10000 -m TCP -T 1 -v`
5. If using test script, evaluate the delivery ratio, if not, query the graylog journal and/or elasticsearch using the correlation id above.

## Context
This issue requires us to use GELF over HTTP, which is inherently slower than TCP. 
Note: Also tried raising the TCP receive buffer to 50 megabytes but problem still persists.
Problem seems to be at its worse when graylog is under heavy load and concurrent TCP sends are in progress.

## Your Environment
Using the following docker compose file
```
version: "3"
services:
  bd-mongo:
    image: "mongo:3"
    volumes:
      - ./data/mongo:/data/db
  bd-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:latest
    volumes:
      - ./data/graylog/data/journal:/usr/share/graylog/data/journal
      - ./data/graylog/config:/usr/share/graylog/data/config
      - ./data/graylog/plugin:/usr/share/graylog/plugin
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://localhost:9000/api
      GRAYLOG_SERVER_JAVA_OPTS: -Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n
    links:
      - bd-mongo:mongo
      - bd-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "12201:12201/udp"
      - "9999:9999"
      - "9999:9999/udp"
```

* Graylog Version: Graylog v2.2.3+7adc951
* Elasticsearch Version: 2.3
* MongoDB Version: 3
* Operating System: CentOS 7 and Mac OS 10.12.5
* Browser version: N/A
