### ISSUE TITLE
Graylog creates duplicate stream with API

### ISSUE THREAD

**Issue by iredmail** [Graylog2/graylog2-server#4073]
Create new stream (with Ansible) with API `POST /streams`, it creates duplicate streams.

Sample JSON used to create steam:

```
{
    "title": "{{ graylog_stream_default_name }}",
    "description": "Logs from all cluster nodes",
    "remove_matches_from_default_stream": true,
    "index_set_id": "{{ _graylog_default_indexset_id }}",
    "matching_type": "AND",
    "rules": []
}
```

Sample Ansible code used to send http POST:

```
- name: "Create stream for cluster nodes."
  uri:
      url: "{{ graylog_rest_base_url }}/streams"
      method: POST
      force_basic_auth: yes
      user: "{{ graylog_admin_username }}"
      password: "{{ graylog_admin_password }}"
      body_format: json
      body: "{{ lookup('template', 'templates/graylog/streams/default.json') }}"
      status_code: 201
```

* Graylog Version: 2.3
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04 LTS
