### ISSUE TITLE
ElasticSearch index is not reachable by Graylog on 2.3.1 using docker-compose

### ISSUE THREAD

**Issue by MathieuMailhos** [Graylog2/graylog2-server#4184]
Hello,

## Expected Behavior

When starting docker-compose with latest Graylog image, graylog is not able to access elasticsearch, resulting concretely with codes 500 on the dashboard. It is expected to be able to build and run fine, obviously.

## Steps to Reproduce

Build the architecture with that docker compose file:

```
version: '2'
services:
  mongo:
    image: mongo:3
    volumes:
      - /graylog/data/mongo:/data/db
  elasticsearch:
    image: elasticsearch:2
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.3.1-1
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
      - /graylog/config:/usr/share/graylog/data/config
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 514:514
```

## Context

When running `docker-compose up` on the above file, Graylog is not able to access elasticsearch indexer on localhost:9200. Graylog version is used `2.3.1-1`. The exact same docker-compose file has been working well with Graylog `2.2.3-1`. 

This error is printed out:

```
org.graylog2.indexer.messages.Messages - Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://127.0.0.1:9200
```

However, no manual issue:
```
 curl localhost:9200
{
  "name" : "Killpower",
  "cluster_name" : "graylog",
  "cluster_uuid" : "sKrmWWiCTMGCnjTSTr9SZw",
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "c849dd13904f53e63e88efc33b2ceeda0b6a1276",
    "build_timestamp" : "2017-04-24T16:18:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```

* Graylog Version: 2.3.1-1
* Elasticsearch Version: 2.4.5
