### ISSUE TITLE
Configure Beats Inputs,create input|output|snippet doesn't work 

### ISSUE THREAD

**Issue by vla** [Graylog2/graylog2-server#4241]
API call error

URL /plugins/org.graylog.plugins.collector/configurations/{id}/inputs 

json body
``` 
 {"backend":"filebeat","type":"file","name":"filebeat-input","properties":{"paths":"['/var/log/docker.log']","scan_frequency":"10s","encoding":"utf-8","ignore_older":"0","document_type":"log","exclude_lines":"[]","include_lines":"[]","tail_files":true}}
```

response body
```
{
  "type": "ApiError",
  "message": "Can not construct instance of org.graylog.plugins.collector.configurations.rest.models.CollectorInput, problem: Null forwardTo\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@6a8b254b; line: 1, column: 253]"
}

```

![e2](https://user-images.githubusercontent.com/230309/31536163-3a029c1c-b030-11e7-8ea0-39c9c3753730.png)

![error](https://user-images.githubusercontent.com/230309/31536093-09502e90-b030-11e7-868d-bf57bef1b31a.png)

docker-compose.yml

``` 
version: '2'
services:
  mongo:
    image: mongo:3.5
    volumes:
    - /etc/localtime:/etc/localtime:ro
  graylog:
    image: graylog/graylog:2.3
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: http://johnwu-dev-rancher:9000/api
      GRAYLOG_MONGODB_URI: mongodb://mongo/graylog
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_ELASTICSEARCH_SHARDS: '1'
      GRAYLOG_ELASTICSEARCH_REPLICAS: '0'
      GRAYLOG_ELASTICSEARCH_INDEX_PREFIX: graylog
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/app/graylog/data/journal:/usr/share/graylog/data/journal
    logging:
      driver: json-file
    links:
    - es:elasticsearch
    - mongo:mongo
    ports:
    - 9000:9000/tcp
    - 12201:12201/tcp
    - 514:514/tcp
    - 514:514/udp
    - 12201:12201/udp
    - 5044:5044/tcp
    - 5044:5044/udp
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      node.name: docker-node-1
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.name: docker-cluster
      discovery.type: single-node
      xpack.security.enabled: 'false'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
```

* account:admin
* Graylog Version: 2.3.1+9f2c6ef 
* Elasticsearch Version: elasticsearch:5.6.3
* MongoDB Version: 3.5
* Operating System: centos7.4
* Browser version: chrome
