### ISSUE TITLE
Cannot receive data from collector-sidecar

### ISSUE THREAD

**Issue by tlytg456** [Graylog2/graylog2-server#4263]
## Expected Behavior

Thank you all.

I want to use graylog to collect tomcat log from Client.
I have installed graylog-collector-sidecar and nxlog on it, and configure the tag correctly.
Now the Client can run the software normally.
```
graylog-collector-sidecar 
INFO[0000] Using collector-id: 6082886b-0962-4697-a4e4-b62ce6876dbd 
INFO[0000] Fetching configurations tagged by: [tomcat]  
INFO[0000] Starting signal distributor                  
INFO[0000] [nxlog] Starting (exec driver)               
INFO[0010] [nxlog] Configuration change detected, rewriting configuration file. 
INFO[0010] [nxlog] Stopping                             
INFO[0013] [nxlog] Starting (exec driver)           
```    
And on web console, I can see the log file.  I expect I could see the receive data when I click 'show message' button in collectors page.

## Current Behavior

But now, when I click that, the page show 'Nothing found'. I also set the tag to output the data to 12344 port, and I expect to establish a global input to show it, but it does not work

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version: 5.6.3
* MongoDB Version: 2.4.9
* Operating System: server: ubuntu 16.04, client: ubuntu 14.04
* Browser version: Chrome 61.0.3163.100 (Official Build) (64-bit)

**Comment by joschi** [comment]
@tlytg456 Please post the complete configuration of the Graylog Collector Sidecar and the generated configuration for NXLOG.

**Comment by tlytg456** [comment]
@joschi Thanks

**Comment by tlytg456** [comment]
@joschi Thanks,
The collector_sidecar.yml files is following:
```
server_url: http://172.26.131.130:9000/api/
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
    - /var/log/tomcat/raptor
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
cache_path: /var/cache/graylog/collector-sidecar
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - tomcat
backends:
    - name: nxlog
      enabled: true
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/graylog/collector-sidecar/generated/nxlog.conf
    - name: filebeat
      enabled: false
      binary_path: /usr/bin/filebeat
      configuration_path: /etc/graylog/collector-sidecar/generated/filebeat.yml
```
and the nxlog.conf is
```
define ROOT /usr/bin

<Extension gelf>
  Module xm_gelf
</Extension>
```
I can see the log file name and path in the collector item page, also the file changed can be seen.

Thanks.

**Comment by joschi** [comment]
> and the nxlog.conf is

Is that really the file located at `/etc/graylog/collector-sidecar/generated/nxlog.conf`?

**Comment by tlytg456** [comment]
@joschi Yes
I also, use the filebeat to do that.
the configure file are showed below:
```
server_url: http://172.26.131.130:9000/api/
update_interval: 10
tls_skip_verify: true
send_status: true
list_log_files:
    - /var/log
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
cache_path: /var/cache/graylog/collector-sidecar
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - tomcat
backends:
    - name: nxlog
      enabled: false
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/graylog/collector-sidecar/generated/nxlog.conf
    - name: filebeat
      enabled: true
      binary_path: /usr/bin/filebeat
      configuration_path: /etc/graylog/collector-sidecar/generated/filebeat.yml

```
and the /etc/graylog/collector-sidecar/generated/filebeat.yml  is

```
filebeat:
  prospectors:
  - encoding: utf-8
    fields:
      collector_node_id: graylog-collector-sidecar
      gl2_source_collector: 6082886b-0962-4697-a4e4-b62ce6876dbd
      type: log
    ignore_older: 0
    multiline:
      match: before
      negate: false
      pattern: ""
    paths:
    - /var/log/*
    scan_frequency: 10s
    tail_files: true
    type: log
output:
  logstash:
    hosts:
    - 172.26.131.130:50440
path:
  data: /var/cache/graylog/collector-sidecar/filebeat/data
  logs: /var/log/graylog/collector-sidecar
tags:
- tomcat

```

but it also does not work......
