### ISSUE TITLE
Can not get the webserver in new install graylog2/docker

### ISSUE THREAD

**Issue by paries** [Graylog2/graylog2-server#4296]
Hello, 
I am using docker on windows 10. this is a new install
Using docker-compose.yml i issue the command 
`docker-compose up`
When everything starts and i try to access the web page@ http://192.168.1.101:9000
i get the error

> Error message
> Request has been terminated
> Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
> Original Request
> GET http://0.0.0.0:9000/api/system/sessions
> Status code
> undefined
> Full error message
> Error: Request has been terminated
> Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

thanks for any help

this is the docker-compose.yml
```
version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.3.0-1
    volumes:
      - c:/graylog/config:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=xxx
      - GRAYLOG_ROOT_PASSWORD_SHA2=xxx
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/api
      - GRAYLOG_WEB_LISTEN_URI=http://0.0.0.0:9000/
      - GRAYLOG_ROOT_TIMEZONE=America/Denver
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
```

docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                                                    NAMES
647582e939bc        graylog/graylog:2.3.0-1                               "/docker-entrypoin..."   12 minutes ago      Up 12 minutes       0.0.0.0:514->514/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:12201->12201/tcp, 0.0.0.0:12201->12201/udp   par_graylog_1
86c3e87f978a        mongo:3                                               "docker-entrypoint..."   13 minutes ago      Up 12 minutes       27017/tcp                                                                                                                par_mongodb_1
2e6cfa86b142        docker.elastic.co/elasticsearch/elasticsearch:5.5.1   "/bin/bash bin/es-..."   13 minutes ago      Up 12 minutes       9200/tcp, 9300/tcp                                                                                                       par_elasticsearch_1
