### ISSUE TITLE
Wrong highlighting of search word.

### ISSUE THREAD

**Issue by omgwtfpwnzor** [Graylog2/graylog2-server#4342]
Hi again, have a problem with misplaced highlighted search results.
![pasted image at 2017_11_13 11_59 am](https://user-images.githubusercontent.com/33115605/32724450-69df51d6-c882-11e7-9bfa-ad50ea9db147.png)

**Comment by joschi** [comment]
@omgwtfpwnzor Please provide all information that's asked for in the issue template:
https://github.com/Graylog2/graylog2-server/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by omgwtfpwnzor** [comment]
Expected behavior: Expecting that graylog will highlight typed word.
Current behavior: Highlighted word misplaced on length of tag (eg. "dev - qa-handler-logs - ", "dev - qa-mdm-logs - ")
Possible solution: none, but tag is not take into account.

Steps to reproduce:
1. Create docker-compose file on monitored host (bla.example.com) with next:
frontend:
    container_name: bla-frontend
    image: bla
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logs.example.com:12201"
        tag: "bla-front-logs"
    ports:
      - "82:80
2. Type in Source tab search string


Environment:
Graylog version: 2.3.2-2 (docker image graylog2/server:2.3.2-2)
Elasticsearch Version: 2 (docker image elasticsearch:2)
MongoDB Version: 3 (docker image mongo:3)
Operating System: CentOS 7.3.1611
Browser version: Chrome 62.0.3202.75 (Official Build) (64-bit)

**Comment by edmundoa** [comment]
Hello @omgwtfpwnzor,

Sorry, but those steps to reproduce the issue are not complete. We need to know what steps you did to get you into that situation so that we can see the issue ourselves and fix it. Would you be so kind as to describe what you did (specially in the web interface) in order to see the screenshot above?

Thank you.

**Comment by omgwtfpwnzor** [comment]
Steps to reproduce the problem:
1. Install graylog server from docker image graylog2/server2.3.2-2 + elasticsearch:2 + mongodb:3
2. On monitored host start containers described in docker-compose file, where added parameters that docker will use gelf logging driver and added custom tag for each container (example of container description in the post above). 
2. Start and log in to graylog server ui
3. Go to tab System and create input GELF UDP: 
  - bind address: 0.0.0.0
  - port: 12201
other parametes - default
4. Next move to tab Source 
 - in time period parametes choose any
 - in search field type for example - error
5. And that's it.

**Comment by joschi** [comment]
@omgwtfpwnzor 
> Install graylog server from docker image graylog2/server2.3.2-2 + elasticsearch:2 + mongodb:3

Please provide your complete configuration for these containers (e. g. your `docker-compose.yml` file).

> in search field type for example - error

Which error? What's in the logs of the Graylog node at that time?

**Comment by omgwtfpwnzor** [comment]
1. [docker-compose.txt](https://github.com/Graylog2/graylog2-server/files/1481790/docker-compose.txt)

2. We've just entered word "error"
At the moment of experimentation in logs:

2017-11-17 10:27:49,638 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
2017-11-17 10:32:49,637 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
2017-11-17 10:32:49,638 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
2017-11-17 10:37:49,637 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
2017-11-17 10:37:49,638 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
2017-11-17 10:42:49,637 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
2017-11-17 10:42:49,638 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.

**Comment by joschi** [comment]
I'm unable to reproduce the issue with Graylog 2.4.0 and the following `docker-compose.yml` file:

```yaml
version: "2"
services:
  some-mongo:
    image: "mongo:3"
  some-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.4.0-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1/api/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "80:9000"
      - "12201:12201/udp"
```

@omgwtfpwnzor Feel free to comment on this issue if the problem still occurs on Graylog 2.4.0 for you.
