### ISSUE TITLE
Extractor Copy Input Date Converter - Parsing EPOCH time but throwing error on logs

### ISSUE THREAD

**Issue by mdiazcl** [Graylog2/graylog2-server#4370]
I have a field called "dtime" where I have the epoch time of that log event. I use a Copy Input extractor targeting timestamp field used Date Converter. Graylog does successfully transform epoch to timestamp and logs are proccessing as expected, but the server error logs it's plagued with errors over that converter, but it's working!

## Expected Behavior
Using UNIX as **Format String** should work for EPOCH based date fields without throwing errors. It works but it's throwing lots of "Could not apply converter [date] of extractor"

`ERROR [Extractor] Could not apply converter [date] of extractor [7f55a1ad-d057-11e7-bd47-286ed488c82c]. java.lang.IllegalArgumentException: Illegal pattern component: U`

I know that the error means that the Format String "UNIX" is not recognized as a valid date string format, nonetheless is doing a correct parsing of that field.

## Possible Solution
Add a date convertor that identifies Epoch date fields without throwing errors.

## Steps to Reproduce (for bugs)
1. Have logs with a datetime field based on Epoch
2. Create an Copy Input extractor
3. Add a Date converter over that field
4. Use **UNIX** as format String

## Context
This is a weird bug, because it works as expected but my graylog server error logs it's full of errors.

## Your Environment
* Graylog Version: 2.4.0-beta.2+2364772 
* Elasticsearch Version: 5.6.4
* MongoDB Version: 
* Operating System: Ubuntu 16.04
* Browser version: Firefox Quantum

**Comment by joschi** [comment]
@mdiazcl What's the actual message your sending to Graylog?

**Comment by mdiazcl** [comment]
I'm complety sure... If I use that extractor/converter all my logs timestamps are displayed correctly (GMT-4). If I remove that extractor the errors disappear but my logs starts defacing over time (going back to default timestamp)

**Comment by joschi** [comment]
I've been trying to reproduce the issue on Graylog 2.4.0-beta.2, but (as expected) the Date converter fails to recognize the invalid date pattern "UNIX" and Graylog simply copies the old, unconverted string value to the new field.

**Logs of Graylog**
```text
graylog_1        | 2017-11-23 16:17:03,994 ERROR: org.graylog2.plugin.inputs.Extractor - Could not apply converter [date] of extractor [bc71fd60-d069-11e7-9608-0242ac120004].
graylog_1        | java.lang.IllegalArgumentException: Illegal pattern component: U
graylog_1        | 	at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566) ~[graylog.jar:?]
graylog_1        | 	at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687) ~[graylog.jar:?]
graylog_1        | 	at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.inputs.converters.DateConverter.convert(DateConverter.java:75) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:260) [graylog.jar:?]
graylog_1        | 	at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:247) [graylog.jar:?]
graylog_1        | 	at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:77) [graylog.jar:?]
```
**Sent message (via netcat to a Raw/Plaintext TCP input)**
```text
$ echo 'logver=54 dtime=1511440375 devid=foo' | nc 127.0.0.1 5555
```

**Resulting message**
![Message in Graylog](https://user-images.githubusercontent.com/43951/33182157-11f55026-d073-11e7-990c-e530a8d3aa66.png)

**Used extractors**
![Extractors](https://user-images.githubusercontent.com/43951/33182170-1f7760ea-d073-11e7-9c54-b0a46be75400.png)

```json
{
  "extractors": [
    {
      "title": "k/v pairs",
      "extractor_type": "copy_input",
      "converters": [
        {
          "type": "tokenizer",
          "config": {}
        }
      ],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "kv",
      "extractor_config": {},
      "condition_type": "none",
      "condition_value": ""
    },
    {
      "title": "dtime",
      "extractor_type": "copy_input",
      "converters": [
        {
          "type": "date",
          "config": {
            "date_format": "UNIX",
            "time_zone": "Europe/Berlin",
            "locale": "de"
          }
        }
      ],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "dtime",
      "target_field": "datetime",
      "extractor_config": {},
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "2.4.0-beta.2"
}
```

**Used `docker-compose.yml`**
```yaml
version: '2'
services:
  mongodb:
    image: mongo:3
    ports:
      - 27017:27017
    mem_limit: 64m
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512m
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.0-beta.2-1
    mem_limit: 1g
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000
      - 5555:5555
```
