### ISSUE TITLE
webui broken after upgrade from 2.2.2 to 2.4.1 and then to 2.4.3

### ISSUE THREAD

**Issue by nrobert13** [Graylog2/graylog2-server#4564]
## Expected Behavior

The web-ui to load and present a login screen.

## Current Behavior

Nothing shows.
Looking at the network traffic in the browser I see the following:
the first request failing is:

Request URL: 
```
http://example.com/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.469e61e05c1640d36297.js
```
Response: 
```
type | ApiError
-- | --
message | java.nio.file.FileSystemNotFoundException: /usr/share/graylog-server/plugin/graylog-plugin-pipeline-processor-2.4.1.jar
```
So for some reasons it is still looking for the 2.4.1 version of the plugin, but only the 2.4.3 is in place.

## Steps to Reproduce (for bugs)

1. install graylog 2.2.2
2. update to 2.4.1
3. update to 2.4.3
4.

## Your Environment

* Graylog Version: 2.4.3
* Elasticsearch Version: 5.6.7
* MongoDB Version: 3.4.9
* Operating System: centos 7.4
* Browser version: chrome 60, firefox 57.0.4

**Comment by joschi** [comment]
@nrobert13 Make sure that you've upgraded Graylog properly, that all old plugin artifacts have been removed from the plugin directory, and that you've reloaded the application in your browser.

A page refresh should do, but you can also try purging your browser cache.

**Comment by nrobert13** [comment]
here's the content of the plugin dir:

```
# ls -l /usr/share/graylog-server/plugin/
total 37952
-rw-r--r-- 1 root root 13997198 Jan 24 23:32 graylog-plugin-aws-2.4.3.jar
-rw-r--r-- 1 root root    27034 Jan 24 23:32 graylog-plugin-beats-2.4.3.jar
-rw-r--r-- 1 root root    60153 Jan 24 23:32 graylog-plugin-cef-2.4.3.jar
-rw-r--r-- 1 root root  2971112 Jan 24 23:32 graylog-plugin-collector-2.4.3.jar
-rw-r--r-- 1 root root  4296855 Jan 24 23:32 graylog-plugin-enterprise-integration-2.4.3.jar
-rw-r--r-- 1 root root  6617711 Jan 24 23:32 graylog-plugin-map-widget-2.4.3.jar
-rw-r--r-- 1 root root   705987 Jan 24 23:32 graylog-plugin-netflow-2.4.3.jar
-rw-r--r-- 1 root root  5594731 Jan 24 23:32 graylog-plugin-pipeline-processor-2.4.3.jar
-rw-r--r-- 1 root root  4574666 Jan 24 23:32 graylog-plugin-threatintel-2.4.3.jar

```

did reload the page many times, also tried in a private window which is supposed to be a clean browser instance without any cache. same behavior on many different computers ...

**Comment by joschi** [comment]
@nrobert13 I'm unable to reproduce the issue on a fresh Graylog 2.4.3 setup (via Docker).

Make sure that there's no caching proxy in between you and the Graylog node.

Used `docker-compose.yml` for reproducing the issue:
```
version: '2'
services:
  mongo:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512m
  graylog:
    image: graylog/graylog:2.4.3-1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MESSAGE_JOURNAL_ENABLED=false
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
```
