### ISSUE TITLE
User Create and Update API returns 500 error when unexisting role name is included in roles request parameters

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Graylog2/graylog2-server#4665]
## Expected Behavior

Returns the 4xx error and appropriate error message.

## Current Behavior

Response Body

```json
{
  "type": "ApiError",
  "message": ""
}
```

Response Code: 500

### In case User Create API

Run a User Create API request whose roles parameter has unexisting role name.
It is convenient to use the API browser.

http://localhost:9000/api/api-browser#!/Users/create_post_1

Show the sample request body.

```json
{
  "username": "foo",
  "email": "foo@example.com",
  "full_name": "foo",
  "permissions": ["*"],
  "password": "password",
  "roles": ["unknown"]
}
```

### In case User Update API

Run a User Update API request whose roles parameter has unexisting role name.
It is convenient to use the API browser.

http://localhost:9000/api/api-browser#!/Users/changeUser_put_2

Show the sample request body.

username: foo

```json
{
  "email": "foo@example.com",
  "full_name": "foo",
  "permissions": ["*"],
  "password": "password",
  "roles": ["unknown"]
}
```

## Your Environment

* Graylog Version: 2.4.3-1
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3
* Operating System: Mac OS X
* Browser version: Google Chrome 65.0.3325.162 (Official Build) (64 bit)

Show the docker-compose.yml which I use.

```yaml
---
version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.3-1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
```
