### ISSUE TITLE
how to save inputs in docker

### ISSUE THREAD

**Issue by lly835** [Graylog2/graylog2-server#5258]
i recreate graylog contains, i should edit inputs every time.

<img width="732" alt="2018-11-02 14 52 56" src="https://user-images.githubusercontent.com/2225913/47898130-84980b00-deaf-11e8-9458-712beebcbd16.png">

docker-compose.yaml

```
version: '2'
services:
  graylog-es:
    image: 'elasticsearch:2'
    hostname: graylog-es
    restart: always
    environment:
      es.cluster.name: graylog
    ports:
      - 9200
      - 9300
  graylog-mongo:
    image: 'mongo:2'
    hostname: graylog-mongo
    restart: always
  graylog:
    image: 'graylog2/server:2.3.2-2'
    hostname: graylog
    restart: always
    depends_on:
      - graylog-es
      - graylog-mongo
    environment:
      GRAYLOG_ROOT_TIMEZONE: Asia/Shanghai
      GRAYLOG_ELASTICSEARCH_HOSTS: http://graylog-es:9200
      GRAYLOG_ROTATION_STRATEGY: size
      GRAYLOG_ELASTICSEARCH_MAX_SIZE_PER_INDEX: 1073741824
      GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_INDICES: 2
      GRAYLOG_ELASTICSEARCH_INDEX_PREFIX: graylog-dev
      GRAYLOG_WEB_ENDPOINT_URI: http://172.20.4.250:9000/api
    ports:
      - 9000:9000
      - 12201:12201/udp
    links:
      - graylog-mongo:mongo
```
