### ISSUE TITLE
Why did you break Content Alert Condition in 3.0 

### ISSUE THREAD

**Issue by mahnunchik** [Graylog2/graylog2-server#5794]
Why did you break Content Alert Condition in 3.0 ? It is not cool! I've lost a bunch of `error` alerts!

## Expected Behavior

Alert type:  Content Alert Condition
Field: `message`
Value: `*error`
Global setting: `GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"`

Match message: `KeyError: ('coordinates', 'occurred at index 1101')`

## Current Behavior

`KeyError: ('coordinates', 'occurred at index 1101')` not matched by `*error`

## Possible Solution

FIX IT AS IT WAS IN VERSION 2

## Your Environment

* Graylog Version: `graylog/graylog:3.0`
* Elasticsearch Version: `docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2`
* MongoDB Version: `mongo:3.6`
* Operating System: Ubuntu 18.04
* Browser version: Netscape navigator 2.0

**Comment by mahnunchik** [comment]
Message: `KeyError: ('CRK', 'occurred at index 3991')`

![image](https://user-images.githubusercontent.com/780935/56030876-a0d58900-5d26-11e9-9ac5-9cbab5b2fc58.png)

Alert haven't been triggered.

**Comment by dennisoelkers** [comment]
@mahnunchik: From which 2.x version of Graylog did you upgrade to 3.x?

**Comment by dennisoelkers** [comment]
I tried to verify the issue in 2.5.2 and it does not work either. Are you sure that you did not change the alert condition or the message format? Did you change the ES version you are using? If yes, from which version to which one?

**Comment by mahnunchik** [comment]
Hi @dennisoelkers 

Current environment:

```yml
services:

  mongo:
    image: mongo:4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1

  graylog:
    image: graylog/graylog:3.0
```

Previous environment:

```yml
services:

  mongo:
    image: mongo:3.6

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4

  graylog:
    image: graylog/graylog:2.5

```

I didn't change any alert conditions.
