### ISSUE TITLE
Couldn't read cluster health for indices [graylog_*] (Could not connect to http://elasticsearch:9200)

### ISSUE THREAD

**Issue by lly835** [Graylog2/graylog2-server#5864]
i use code from http://docs.graylog.org/en/stable/pages/installation/docker.html
```
version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
```

os is mac. docker version
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

error logs.
```
graylog_1        | 2019-03-21 10:02:16,387 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRangesCleanupPeriodical] periodical in [15s], polling every [3600s].
graylog_1        | 2019-03-21 10:02:16,408 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*] (Could not connect to http://elasticsearch:9200)
graylog_1        | 2019-03-21 10:02:16,411 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
graylog_1        | 2019-03-21 10:02:16,414 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
graylog_1        | 2019-03-21 10:02:16,448 INFO : org.graylog2.shared.initializers.PeriodicalsService - Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Not configured to run on this node.
graylog_1        | 2019-03-21 10:02:16,448 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.AlarmCallbacksMigrationPeriodical] periodical, running forever.
graylog_1        | 2019-03-21 10:02:16,466 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical, running forever.
graylog_1        | 2019-03-21 10:02:16,470 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical, running forever.
graylog_1        | 2019-03-21 10:02:16,472 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexFailuresPeriodical] periodical, running forever.
graylog_1        | 2019-03-21 10:02:16,473 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.TrafficCounterCalculator] periodical in [0s], polling every [1s].
graylog_1        | 2019-03-21 10:02:16,488 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical] periodical in [0s], polling every [3600s].
graylog_1        | 2019-03-21 10:02:16,507 INFO : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Cluster not connected yet, delaying index field type initialization until it is reachable.
graylog_1        | 2019-03-21 10:02:16,518 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.sidecar.periodical.PurgeExpiredSidecarsThread] periodical in [0s], polling every [600s].
graylog_1        | 2019-03-21 10:02:16,547 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.sidecar.periodical.PurgeExpiredConfigurationUploads] periodical in [0s], polling every [600s].
graylog_1        | 2019-03-21 10:02:16,577 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
mongodb_1        | 2019-03-21T10:02:16.594+0000 I NETWORK  [listener] connection accepted from 172.22.0.4:41490 #4 (4 connections now open)
mongodb_1        | 2019-03-21T10:02:16.607+0000 I NETWORK  [conn4] received client metadata from 172.22.0.4:41490 conn4: { driver: { name: "mongo-java-driver", version: "unknown" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.9.125-linuxkit" }, platform: "Java/Oracle Corporation/1.8.0_212-8u212-b01-1~deb9u1-b01" }
graylog_1        | 2019-03-21 10:02:16,611 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:4}] to mongo:27017
graylog_1        | 2019-03-21 10:02:16,719 INFO : org.graylog2.migrations.V20161130141500_DefaultStreamRecalcIndexRanges - Cluster not connected yet, delaying migration until it is reachable.
graylog_1        | 2019-03-21 10:02:16,800 INFO : org.graylog2.shared.initializers.JerseyService - Enabling CORS for HTTP endpoint
elasticsearch_1  | [2019-03-21T10:02:19,238][INFO ][o.e.c.s.MasterService    ] [Tl7hMhg] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {Tl7hMhg}{Tl7hMhgMSjyiz73XgTrWRg}{3X47RJLxRtGG1BamuI7ucA}{localhost}{127.0.0.1:9300}
elasticsearch_1  | [2019-03-21T10:02:19,258][INFO ][o.e.c.s.ClusterApplierService] [Tl7hMhg] new_master {Tl7hMhg}{Tl7hMhgMSjyiz73XgTrWRg}{3X47RJLxRtGG1BamuI7ucA}{localhost}{127.0.0.1:9300}, reason: apply cluster state (from master [master {Tl7hMhg}{Tl7hMhgMSjyiz73XgTrWRg}{3X47RJLxRtGG1BamuI7ucA}{localhost}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
elasticsearch_1  | [2019-03-21T10:02:19,338][INFO ][o.e.h.n.Netty4HttpServerTransport] [Tl7hMhg] publish_address {172.22.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2019-03-21T10:02:19,339][INFO ][o.e.n.Node               ] [Tl7hMhg] started
elasticsearch_1  | [2019-03-21T10:02:19,741][INFO ][o.e.g.GatewayService     ] [Tl7hMhg] recovered [1] indices into cluster_state
elasticsearch_1  | [2019-03-21T10:02:20,178][INFO ][o.e.c.r.a.AllocationService] [Tl7hMhg] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[graylog_0][3], [graylog_0][2], [graylog_0][1]] ...]).
```
