### ISSUE TITLE
Graylog GELF HTTP Ignoring TCP Keep Alive

### ISSUE THREAD

**Issue by Aenima4six2** [Graylog2/graylog2-server#6829]
Graylog GELF HTTP Input is ignoring TCP Keep-Alive packets sent from clients.

## Expected Behavior
TCP Keep Alive packets should reset the `Idle writer timeout`, extending the active TCP session.

## Current Behavior
 Graylog server appears to always close a connection after the `Idle writer timeout` has been reached, regardless whether a client has sent TCP Keep Alive packets.

![image](https://user-images.githubusercontent.com/2087362/69178028-c0ac0700-0ad6-11ea-8581-a3d89618ed29.png)
_Above you can see Traefik (10.0.0.80) issue a Keep-Alive to Graylog (10.0.0.87), Graylog ACKS back, but the connection is terminated 30 seconds later_ 

## Possible Solution
Listen for RFC compliant TCP Keep alive packets, and when received, reset any active Idle writer timeout`. Alternatively, reduce the logger severity of this item to a `WARN` or `INFO`.

## Steps to Reproduce (for bugs)

Sample stack
```
version: '2'
services:
  traefik:
    image: "traefik:v2.0.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.graylogWeb.address=:80"
      - "--entryPoints.graylogGelfHttp.address=:12204"
      - "--entryPoints.graylogGelfHttp.transport.respondingTimeouts.writeTimeout=15"
    ports:
      - "8080:8080" # Traefik Web
      - "80:80" # Graylog Web
      - "12204:12204" # Gelf HTTP
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
                
  mongodb:
    image: mongo:3
  
  elasticsearch:
    image: elasticsearch:5.6
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    
  graylog:
    image: graylog/graylog:3.1.3
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.locall/
    volumes:
      - "./plugins/:/usr/share/graylog/plugin/"
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    labels:
      - "traefik.enable=true"
      # Graylog Web
      - "traefik.http.services.graylog.loadbalancer.server.port=9000"
      - "traefik.http.services.graylog.loadbalancer.healthcheck.path=/api/system/lbstatus"
      - "traefik.http.services.graylog.loadbalancer.healthcheck.port=9000"
      - "traefik.http.services.graylog.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.graylog.loadbalancer.healthcheck.timeout=2m"
      - "traefik.http.services.graylog.loadbalancer.healthcheck.scheme=http"
      - "traefik.http.routers.graylog.service=graylog"
      - "traefik.http.routers.graylog.rule=Host(`graylog.local`)"
      - "traefik.http.routers.graylog.entryPoints=graylogWeb"
      # Gelf HTTP
      - "traefik.http.services.graylog2.loadbalancer.server.port=12204"
      - "traefik.http.routers.graylog2.service=graylog2"
      - "traefik.http.routers.graylog2.rule=Host(`graylog.local`)"
      - "traefik.http.routers.graylog2.entryPoints=graylogGelfHttp"
```
1. Add a host file entry for `graylog.local 127.0.0.1`
1. `docker-compose up` the provided YAML in a `docker-compose.yml` file. Traefik will load balance HTTP Gelf traffic on port 12204.
2. Add an HTTP Input in Graylog to port 12204 with a `Idle writer timeout` of `20` seconds.
3. Send GELF HTTP logs with any client of choice to `localhost:12204`, and wait `30` seconds between `POSTS`.
4. Oberve timeout exceptions similar to ...
```
2019-11-19 17:44:07,895 ERROR: org.graylog2.plugin.inputs.transports.AbstractTcpTransport - Error in Input [GELF HTTP/5cc9f93736182e00011e48ae] (channel [id: 0x11b3491e, L:/10.0.0.90:12204 ! R:/10.0.0.81:54700]) (cause io.netty.handler.timeout.ReadTimeoutException)
```

## Context
This issue causes many `ERROR` log messages in the graylog logs, as well as the reverse proxy having to create more TCP connections.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 5.6
* MongoDB Version: v3.6.13
* Operating System: Docker 19.03.4
* Browser version: Chrome Version 78.0.3904.97 (Official Build) (64-bit)
