### ISSUE TITLE
Periodic Notification of Sidecar agents in Unknown or Failing State

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#7944]
Original request recieved via support ticket:
" I strongly feel that there needs to be something in place to draw our attention to failing sidecars."

## What?

From original request:
"A notification sent out say once a hour with a list of failing sidecars would save us the trouble of having to periodically stop what we are doing and go make sure all sidecars are functioning as expected."

Additional thoughts: 
Perhaps we could create a system event that writes a specific event for each registered sidecar agent that is in an unknown or failing state. Use those events for alerting and visualization/reporting.

## Why?

From the original request: "We potentially could end up with hundreds of sidecars deployed and it could be time consuming to go consuming for failed instances.

I know we could filter on Failed/Unknown from the sidecar administration page but we would need to do it throughout the day to ensure they are all in good health."

## Your Environment

* Graylog Version: unknown
* Elasticsearch Version: uknown
* MongoDB Version: unknown
* Operating System:unknown
* Browser version:unknown

**Comment by valumar** [comment]
Maybe my problem is related to this. 
After upgrading Graylog from version 3.2.3 to 3.3.0 sidecars lost connection with graylog server.
As I investigate it can be related with API token wrong format in MongoDB.

Screenshot from Graylog GUI shows the null instead of right token after upgrading:
![изображение](https://user-images.githubusercontent.com/7857900/83289170-51ce0a00-a1ed-11ea-96e9-4673cbe4d5dc.png)

**Comment by mpfz0r** [comment]
@valumar could you try to look for the string `Encrypting access token` in your `server.log` from when you've started 3.3.0 the first time?
Are there any exceptions surrounding this message?

**Comment by valumar** [comment]
Unfortunately logs has been truncated already

**Comment by mpfz0r** [comment]
Bummer. Do you have a mongodb backup from before you've upgraded to 3.3?

**Comment by valumar** [comment]
> Bummer. Do you have a mongodb backup from before you've upgraded to 3.3?

No, since it's not prod environment.

**Comment by mpfz0r** [comment]
So you do have a copy of that sidecar token in the prod environment?

**Comment by valumar** [comment]
Prod env has other  token.

**Comment by valumar** [comment]
Prod env has other token. But as I understood, old token should be decoded (or encrypted) in mongodb during upgrade, but it does not happen.

**Comment by mpfz0r** [comment]
Yeah, unfortunately it clobbered the old token with `null`. So it's lost forever.

There must be something special in your environment, because we are not able to reproduce that bug.
Is there anything special about your `password_secret`?

**Comment by mpfz0r** [comment]
Also, what is your environment? Which Linux and JDK version?

**Comment by valumar** [comment]
Prod env has other token. But as I understood, old token should be decoded (or encrypted) in mongodb during upgrade, but it does not happen (don have the key `token_type`).

```
db.getCollection('access_tokens').find({})

/* 2 */
{
    "_id" : ObjectId("5e4a656d2364f10011e10a39"),
    "last_access" : ISODate("2020-05-23T13:13:11.077Z"),
    "token" : "1ia6dmrst4vvg90REDACTED26m1mkgf01935apur",
    "username" : "graylog-sidecar",
    "NAME" : "graylog_sidecar_token"
}

/* 4 */
{
    "_id" : ObjectId("5ed144cfbe8fed0e740b6ab3"),
    "last_access" : ISODate("1970-01-01T00:00:00.000Z"),
    "token_type" : 1,
    "token" : "0cf404f69bc572c6b27REDACTED12029e21f3ac99REDACTED2f1eb345b2abaade641ee089a4c7982751916fafaa37e87b0859a50e8",
    "username" : "graylog-sidecar",
    "NAME" : "graylog_sidecar_token_reuse"
}

```

**Comment by valumar** [comment]
> Also, what is your environment? Which Linux and JDK version?

docker info
```bash
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-1062.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: graylog-main-01.int.fkp
ID: F6HF:J6Z7:X2LQ:M44Y:ICRF:7WSE:CG76:DHV7:KN3A:FAMI:JBLF:WDXR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
```
cat docker-compose.yml
```yaml
version: '2.2'
services:
  mongodb:
    restart: always
    image: mongo:4.2
    hostname: graylog-01
    extra_hosts:
      - "graylog-01:10.REDACTED"
      - "graylog-02:10.REDACTED"
      - "graylog-03:10.REDACTED"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb-keyfile:/opt/keyfile
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 27017:27017
    command: [ "--bind_ip_all", "--keyFile", "/opt/keyfile", "--replSet", "graylogrs" ]
    environment:
      MONGO_INITDB_DATABASE: graylog
      MONGO_INITDB_ROOT_USERNAME: REDACTED
      MONGO_INITDB_ROOT_PASSWORD: REDACTED

  graylog:
    restart: always
    image: graylog/graylog:3.3
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    hostname: graylog-01
    extra_hosts:
      - "graylog-01:10.REDACTED"
      - "graylog-02:10.REDACTED"
      - "graylog-03:10.REDACTED"
    volumes:
      - ./GeoLite2-City.mmdb:/geoip/GeoLite2-City.mmdb
      - graylog_journal:/usr/share/graylog/data/journal
      - /etc/localtime:/etc/localtime:ro
      - ./plugins/metrics-reporter-prometheus-3.0.0.jar:/usr/share/graylog/plugin/metrics-reporter-prometheus-3.0.0.jar
    environment:
      - GRAYLOG_OUTPUT_BATCH_SIZE=100
      - GRAYLOG_PROCESSBUFFER_PROCESSORS=72
      - "GRAYLOG_SERVER_JAVA_OPTS=-Xms6g -Xmx6g"
      - TZ=Europe/Moscow
      - GRAYLOG_IS_MASTER=true
      - GRAYLOG_MONGODB_URI=mongodb://REDACTED:REDACTED@graylog-01:27017,graylog-02:27017,graylog-03:27017/graylog?replicaSet=graylogrs
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://REDACTED:REDACTED@graylog-elasticsearch-01:9201,http://REDACTED:REDACTED@graylog-elasticsearch-02:9201,http://REDACTED:REDACTED@graylog-elasticsearch-03:9201,http://REDACTED:REDACTED@graylog-elasticsearch-04:9201

      - GRAYLOG_PASSWORD_SECRET=REDACTED

      - GRAYLOG_ROOT_PASSWORD_SHA2=REDACTED
      - GRAYLOG_HTTP_EXTERNAL_URI=http://REDACTED:9000/
      - GRAYLOG_HTTP_BIND_ADDRESS=REDACTED:9000
      - GRAYLOG_TRUSTED_PROXIES=REDACTED/32
      - GRAYLOG_HTTP_CONNECT_TIMEOUT=15s
      - GRAYLOG_RING_SIZE=131072
      - GRAYLOG_INPUTBUFFER_RING_SIZE=131072

    depends_on:
      - mongodb
    network_mode: "host"
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # Syslog TCP 1515
      - 1515:1515
      # Syslog UDP 1515
      - 1515:1515/udp
      # Syslog UDP 1516 
      - 1516:1516/udp
      # Filebeat
      - 5044:5044
      # Windows Filebeat
      - 15044:15044
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp


volumes:
  mongo_data:
    driver: local
  mongo_configdb:
    driver: local
  graylog_journal:
    driver: local
```
